### PR TITLE
Multiple queries with syntax errors

### LINKED ISSUE #335: Errors in later semicolon separated commands hide output from earlier commands
E.g.
```
test_db> select 1; select;
syntax error at end of input
LINE 1: select
```

The output from the first command should be printed before the error traceback in the second

### PR DESCRIPTION
**Pull request by amjith**
This fixes #335. 

@darikg  Can you review?

### CODE REVIEW

**Comment by darikg** [comment]
Now after an error, it continues to run queries -- I think it should stop after an error. E.g. the 'select 3' query below shouldn't run.

```
test> select 1; select; select 3;
+------------+                   
|   ?column? |                   
|------------|                   
|          1 |                   
+------------+                   
SELECT 1                         
syntax error at end of input     
LINE 1: select                   
              ^                  
                                 
+------------+                   
|   ?column? |                   
|------------|                   
|          3 |                   
+------------+                   
SELECT 1                         
```

**Comment by amjith** [comment]
This is a conundrum. This new behavior complies with how psql behaves. But I remember making a big deal about stopping the execution of statements if one of them has an error in it.

What are your thoughts on this matter?

**Comment by j-bennet** [comment]
I think it should match psql behavior.

**Comment by darikg** [comment]
It looks like psql has an `ON_ERROR_STOP` variable which controls this behavior

**Comment by amjith** [comment]
I'm torn on the decision. 

I want the default behavior for interactive commands to match psql. But running scripts using `\i` should stop after the first error.

I didn't know about `ON_ERROR_STOP`, but in order to use it we need to add support for `SET` which will toggle the feature at runtime. 

Unless one of you is not happy with the current behavior, let's merge this change as is, then add a new special command or a command-line switch to control this behavior.

**Comment by darikg** [comment]
Agreed

**Pull request merged**
