### PR TITLE
convert enum type to unicode in tabulate. #437

### PR DESCRIPTION
**Pull request by GTxx**
I try to encode string  before it is passed to tabulate. It works for my issue.

### CODE REVIEW

**Comment by amjith** [comment]
There are two ways to fix this. One we can register a type caster in psycopg2 to return us unicode values for enums instead of utf-8. Two we can do what you've done which is to handle it in tabulate. 

I've been resisting the urge to fix this issue in tabulate since we want psycopg2 to do the right thing. But I'm getting tired of playing whack a mole with psycopg2 and I think fixing it in tabulate is a much better option. 

@dbcli/pgcli-core Can you please share your thoughts?

**Comment by amjith** [comment]
BTW, here's a way to reproduce the issue: 

```
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy', '日本語');
CREATE TABLE person (name TEXT, current_mood mood);
INSERT INTO person VALUES ('Moe', '日本語')
SELECT * FROM person;
```

I have a PR that registers a type caster for enum. https://github.com/dbcli/pgcli/pull/440

The question is should we register a type caster as done in PR #440 or should we use this PR to patch it in tabulate?

**Comment by j-bennet** [comment]
@amjith I think that psycopg2 is the right place to fix this, because re-encoding every string in tabulate may affect performance. Why do you prefer the tabulate way?

**Comment by amjith** [comment]
The reason for fixing it in tabulate would be, it'll be a blanket fix that'll handle all the datatypes. Right now we're adding special type casters for each datatype https://github.com/dbcli/pgcli/blob/master/pgcli/pgexecute.py#L16-L21. 

But we still manage to miss corner cases as reported here. But if we handle it in tabulate, then we won't need separate type casters and it'll future proof us from running into corner cases like this.

**Comment by j-bennet** [comment]
@amjith I see what you mean. Do you have any concerns about performance? This is what I measured:
```
$ python -m timeit -s "from encodingutils import utf8tounicode" "utf8tounicode(u'日本語')"
1000000 loops, best of 3: 0.309 usec per loop
```
With 0.3s per conversion, what if we have 100K values to convert in table?

**Comment by darikg** [comment]
@j-bennet I think that's 0.3 microseconds

**Comment by j-bennet** [comment]
@darikg That sounds much better. :)

**Comment by amjith** [comment]
Good point about overhead and thanks for doing the micro-benchmark to show some real numbers. I'm happy with the benchmark and I'm confident that this won't produce a noticeable lag in the print out.

**Comment by j-bennet** [comment]
Agree, with performance concern out of the way, this approach looks good.

**Comment by amjith** [comment]
@GTxx Thanks for the PR. I appreciate it. 

:snowflake:

**Pull request merged**
