### PR TITLE
Better * expansion for inserts

### PR DESCRIPTION
**Pull request by koljonen**
## Description
When expanding * for `INSERT INTO tbl(*`, skip columns that have a default value of either some sequence (`nextval(...`) or of `now()`.

## Checklist
- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by amjith** [comment]
Should this skip columns of type SERIAL as well? Right now I see `id` being suggested by `id` is of type `SERIAL` which should be auto-incremented.

**Comment by amjith** [comment]
How do I trigger this feature? Here's what I'm seeing: 

1__dbcli_0_python2_7_-__pgcli___users_amjith_code_python_pgcli____tmux__and_postgresql_-_add_timestamp_column_with_default_now___for_new_rows_only_-_stack_overflow


I have a column with default set to now() and a column that has a nextval() but both of them are suggested by completion.

**Comment by koljonen** [comment]
@amjith I think `serial` columns are just syntactic sugar for `integer` with a `nextval(...` default, so they should be covered? I get these results on 9.1.24 and 9.6.2:
```
vagrant@vagrant:vagrant> CREATE TABLE bar(id serial);
........................ SELECT att.atttypid::regtype, def.adsrc
........................ FROM pg_attribute att
........................ LEFT OUTER JOIN pg_attrdef def
........................     ON def.adrelid = att.attrelid
........................     AND def.adnum = att.attnum
........................ WHERE att.attrelid = 'bar'::regclass AND att.attname = 'id';
NOTICE:  CREATE TABLE will create implicit sequence "bar_id_seq" for serial column "bar.id"

CREATE TABLE
╒════════════╤═════════════════════════════════╕
│ atttypid   │ adsrc                           │
╞════════════╪═════════════════════════════════╡
│ integer    │ nextval('bar_id_seq'::regclass) │
╘════════════╧═════════════════════════════════╛
SELECT 1
```

**Comment by koljonen** [comment]
@amjith You enter `INSERT INTO test (*` and trigger completion.

**Comment by amjith** [comment]
Awesome! That works as expected. 👍 

Reading through the code now.

**Comment by amjith** [comment]
Is there an advantage in even suggesting the column that have `nextval()` and `now()` in the completion menu?

**Comment by amjith** [comment]
Code looks good. Merging. 👍

**Pull request merged**
