### PR TITLE
Don't include args in function suggestions for backslash commands

### PR DESCRIPTION
**Pull request by koljonen**
## Description
E.g. after `\df`, we want to suggest only function names.
@amjith, you feel like merging this?

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by fpietka** [comment]
@koljonen you have a small lint issue. If you could take a look, it would be great!

**Comment by amjith** [comment]
This puzzles me a bit. Wouldn't be nicer to show the args for custom functions so a user can differentiate between two fuctions with same names but different args?

**Comment by amjith** [comment]
Old behavior: 
1__0_1_python2_7_-__pgcli___users_amjith_code_python_pgcli____tmux_

New behavior:

1__0_1_python2_7_-__pgcli___users_amjith_code_python_pgcli____tmux_

**Comment by koljonen** [comment]
@amjith The problem is this:
```
vagrant@vagrant:vagrant> \df sum
╒════════════╤════════╤════════════════════╤═══════════════════════╤════════╕
│ Schema     │ Name   │ Result data type   │ Argument data types   │ Type   │
╞════════════╪════════╪════════════════════╪═══════════════════════╪════════╡
│ pg_catalog │ sum    │ numeric            │ bigint                │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ double precision   │ double precision      │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ bigint             │ integer               │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ interval           │ interval              │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ money              │ money                 │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ numeric            │ numeric               │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ real               │ real                  │ agg    │
├────────────┼────────┼────────────────────┼───────────────────────┼────────┤
│ pg_catalog │ sum    │ bigint             │ smallint              │ agg    │
╘════════════╧════════╧════════════════════╧═══════════════════════╧════════╛
SELECT 8
Time: 0.006s
vagrant@vagrant:vagrant> \df sum(int)
╒══════════╤════════╤════════════════════╤═══════════════════════╤════════╕
│ Schema   │ Name   │ Result data type   │ Argument data types   │ Type   │
╞══════════╪════════╪════════════════════╪═══════════════════════╪════════╡
╘══════════╧════════╧════════════════════╧═══════════════════════╧════════╛
SELECT 0

```

**Comment by amjith** [comment]
I see, that is a problem. I think for `\df` it makes sense to not show the args but for `\ef` (whenever we get around to implementing that) we should keep the args in the completion.

**Pull request merged**
