### PR TITLE
Show host and user information in prompt

### PR DESCRIPTION
**Pull request by limdauto**
I can also make this configurable if you are keen

screen shot 2016-07-15 at 12 14 08 pm

### CODE REVIEW

**Comment by j-bennet** [comment]
We already made it configurable in mycli:

https://github.com/dbcli/mycli/blob/master/mycli/myclirc#L53-L60

I'd rather port the same functionality to pgcli.

**Comment by limdauto** [comment]
@j-bennet done!

**Comment by j-bennet** [comment]
@limdauto You also need a default there, for users that don't have it in config.

**Comment by limdauto** [comment]
@j-bennet Cool I will add it this weekend. It was just that when I read existing code, it doesn't seem to concern with defaults too much. mycli seems much more robust.

**Comment by limdauto** [comment]
@j-bennet updated!

**Comment by amjith** [comment]
> It was just that when I read existing code here, it doesn't seem too concerned with defaults. mycli seems much more robust in that regards.

I want to address why we didn't deal with defaults in pgcli. It's because when you try to read a value from the config file it is always superimposed on top of the default config file (pgclirc) that is shipped with every version of pgcli. 

So a missing value for prompt in the user's config file won't result in an exception because it will be supplied by the default `pgclirc` file. So even though it is a good practice to supply the default values (as requested by j-bennet) it is not strictly required in order to work.

I'd like to think that we try to maintain the same level of robustness for both mycli as well as pgcli. So if you find that one or the other is lacking in quality, I'll be happy to address them.

**Comment by amjith** [comment]
The functionality in this PR looks great!! Thank you for taking the time to contribute. 🍰 

I'll let @j-bennet do the final review and merge this in.

**Comment by j-bennet** [comment]
Looks good to me. I'd say go ahead and also port overriding prompt at run-time by providing a command line parameter, like mycli does:

https://github.com/dbcli/mycli/blob/master/mycli/main.py#L724-L726

but that's probably an overkill until someone asks for that feature.

Merging.

👍

**Pull request merged**
