### PR TITLE
Switch the location of log/history file based on OS.

### PR DESCRIPTION
**Pull request by amjith**
@j-bennet @darikg I made a reference implementation of what I had in mind. 

You're welcome to test this and merge or write your own implementation if you're not satisfied. 

I haven't tested this yet, sorry.

### CODE REVIEW

**Comment by j-bennet** [comment]
Wow you're fast @amjith. How about I apply this into my appveyor branch and we'll see if it fixes it.

**Comment by j-bennet** [comment]
Yes it fixes the appveyor run problem - it's back to prompt_toolkit problem, just as expected:

https://ci.appveyor.com/project/j-bennet/pgcli/build/job/2gqkdnkftguytn6x

**Comment by j-bennet** [comment]
@amjith This one should be updated too:

https://github.com/dbcli/pgcli/blob/amjith/fix_log_file_windows/pgcli/pgcompleter.py#L21

Otherwise I think the fix is good to go.

**Comment by j-bennet** [comment]
I added another commit that:
* Updates the code that migrates old config with new path.
* Updates named queries loading from the new path.
@darikg or @amjith could you take a look for sanity check and merge?

**Comment by darikg** [comment]
So `config_location()` returns something like `c:\users\username\AppData\Local\dbcli\pgcli\`. But everything that uses it writes `config_location() + 'config'`. What's the point of that `'config'` subfolder?

**Comment by j-bennet** [comment]
@darikg So in new implementation `config_location` does NOT return full path to file. It returns directory name to where the file should be written. To that, we add `config`, `log`, or `history` to get full absolute path.

**Comment by darikg** [comment]
Ahh, so 'config' isn't a subfolder name, it's the filename. Sorry for the misunderstanding

**Comment by amjith** [comment]
I'm replying from my phone on 2G. I couldn't check the commit. So I'll
defer to @darikg to review.

@j-bennet Can you release the next version once this is merged?

Amjith

**Comment by j-bennet** [comment]
Yes. It should be 0.20.1, correct?

**Comment by amjith** [comment]
Yes.

**Comment by darikg** [comment]
I tested it by renaming my current config folder, or recreating the original .pgclirc file to test the migration, and everything looks good

**Pull request merged**
