### PR TITLE
Remove dead code and fix a broken test

### PR DESCRIPTION
**Pull request by koljonen**
I was playing around with [https://www.codacy.com/](Codacy) and found some low-hanging fruit.

### CODE REVIEW

**Comment by darikg** [comment]
@j-bennet Do you know why landscape.io doesn't process PRs anymore? I wonder if it catches the same dead code

**Comment by j-bennet** [comment]
@darikg Nope, no idea.

**Comment by amjith** [comment]
I think landscape.io might have silently stopped. We didn't change anything on our front. 

You're welcome to try setting up codacy for pgcli.

**Comment by darikg** [comment]
I poked around into the landscape.io settings and noticed the bot was turned off. I turned it back on and it seems to be commenting on new PRs... I'll try out automating codacity on my pgcli fork and see if it has a less annoying option than the landscape bot.

**Pull request merged**
