### PR TITLE
Aded sdist upload to release script.

### PR DESCRIPTION
**Pull request by j-bennet**

### CODE REVIEW

**Comment by amjith** [comment]
Thanks! :lollipop:

**Comment by loslots** [comment]
Thanks for your help. It appears my suspicions are correct that my personal life is a bad dream. I don't know where I was seeing it at because it fossa pope are

**Comment by loslots** [comment]
Sorry  not poor.... it disappeared from my phone but I don't think I can see much more than just the same old things that I have been working up to and suspecting for almost two years now. I have been thinking and suspecting that He was chatting to the world of online sex or something like. I'M SORRY IM SUPER CRUSHED BY THIS. But do appreciate the help..

**Comment by j-bennet** [comment]
The bots strike again...

**Comment by loslots** [comment]
bots?

**Pull request merged**
