### PR TITLE
Fix for https://github.com/dbcli/pgcli/issues/1014.

### PR DESCRIPTION
**Pull request by j-bennet**
## Description

Fixes https://github.com/dbcli/pgcli/issues/1014.

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by j-bennet** [comment]
> What will happen in this case if the user executes a pgspecial command that needs a cursor?

It will throw an exception further down the line, in `pgspecial`. Right now, it just throws an exception earlier.

> I notice that \dp is NO_QUERY, but it might actually need a connection to execute. I guess it's fine since it's not actually implemented? I didn't notice any other pgspecial commands that might be problematic.

Whatever actually needs a connection, will break, but I think it's fine, because it also breaks now.

> Should some tests be added for what happens when the connection is closed but the prompt is still open? Should pgcli just exit at that point?

No need to exit. I recently merged a PR to auto-reconnect on connection dropped:

https://github.com/dbcli/pgcli/pull/1009

Automatic reconnect is a feature that `mycli` already had for a while, and it's much more convenient than asking the user if he wants to reconnect every time connection times out. After #1009 was merged, this one is really only handling the edge case where auto-reconnect did not work.

Good point about testing. I will see if I can add a unit or integration test here. It may be a bit of a hassle, what with the additional complexity of killing the connection.

**Comment by j-bennet** [comment]
@maxrothman I added a unit test, would appreciate another look!

**Comment by amjith** [comment]
@j-bennet The test you added seems to be failing. Can you take a look?

**Comment by j-bennet** [comment]
Will do.

**Comment by j-bennet** [comment]
Missed the pep8 problem. Perhaps it's time to black-ify this repo, just like you did for litecli. All good now!

**Comment by amjith** [comment]
:+1:

**Comment by maxrothman** [comment]
Sorry I didn't have time to follow up with your comments. Thanks for getting this one across the finish line @amjith!

**Pull request merged**
