### PR TITLE
Changelog update for 1.5.0

### PR DESCRIPTION
**Pull request by amjith**
@dbcli/pgcli-core Can you please review the changelog and make any necessary edits? 

@j-bennet Can you do a release once this is approved by core team?

### CODE REVIEW

**Comment by j-bennet** [comment]
@amjith Reviewing.

**Comment by j-bennet** [comment]
Looks good to me. There was one more thing, docs for tabulate's number formatting, but that's neither a bugfix nor a feature, so it's fine to omit.
👍

**Comment by amjith** [comment]
Alright people, @dbcli/pgcli-core let's get this reviewed and release a new version.

**Comment by stuartquin** [comment]
I've been using it for the past few days, no issues, things seem really stable.
The version flag is still set to `1.4`, does that get updated after merge?

:+1:

**Comment by amjith** [comment]
@stuartquin I usually bump the version when it's in master but I think @j-bennet does it the other way around. Either way it'll get bumped before published. 😄

**Comment by amjith** [comment]
I think this is ready to merge. @j-bennet Can you do the honors?

**Comment by j-bennet** [comment]
I'll release this tonight.

**Pull request merged**
