### PR TITLE
Add \i path completion

### PR DESCRIPTION
**Pull request by ajlai**
Initial prototype of #467 

@amjith feel free to check it out. Looks like this for me:
image

If you select a directory it will start prompting autocomplete for the next characters you input or for everything if you just press tab.

image

Currently also handles `..` and `~`. What do you think?

### CODE REVIEW

**Comment by amjith** [comment]
@ajlai Thanks for the PR. It works great in my machine.

I was hoping to use the builtin PathCompleter from prompt_toolkit: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/contrib/completers/filesystem.py

Here's an example of how it is used in ptpython: https://github.com/jonathanslenders/ptpython/blob/master/ptpython/completer.py

The advantage in reusing prompt_toolkit's path completer is we get the benefits of bug fixes in the future for free and it is well tested (in all the platforms we support). 

What do you think?

**Comment by ajlai** [comment]
Hey @amjith,
Thanks for the suggestion. I'll take a look at this later tonight.

**Comment by amjith** [comment]
Hi @ajlai, did you get a chance to look into the PathCompleter?

**Comment by ajlai** [comment]
Hi @amjith,
I did take a look at PathCompleter and agree that we should use that instead. I'll have some more time to work on the PR tomorrow.

**Comment by ajlai** [comment]
@amjith I switched it over to PathCompleter. Good suggestion, it looks a lot simpler :smile:.

Please give it a try, it behaves a bit differently since it's now just using the bare PathCompleter completions (need to manually type `/` to enter dirs, no display_meta).

**Comment by amjith** [comment]
@ajlai Thank you for switching over. I've tested it and it looks great. :+1: 

We can add the meta information at a later time. 

@darikg Would you mind trying this in Windows to see if the path completer will work with dos path names?

**Comment by darikg** [comment]
This is great! It works fine in Windows, although it does seem to break when directory names contain spaces. Probably a bug to report upstream to prompt-toolkit.

**Comment by amjith** [comment]
Thanks for testing it @darikg.

**Pull request merged**
