### PR TITLE
Add application name

### LINKED ISSUE #868: Add application_name parameter for Postgres 9.x & 10.x connections
## Feature request
Hi, would it be possible to add `application_name="pgcli"` connection parameter to all connections, for the sake of Postgres 9.x or 10.x? See https://www.postgresql.org/docs/9.0/static/runtime-config-logging.html#GUC-APPLICATION-NAME

With this, database administrators will be able to see "pgcli" connections explicitly in the list of connections for debugging reasons (ie. `SELECT * FROM pg_stat_activity`).

FYI, `psql` and many more UI clients add the application_name by default too.

Thanks for any comments! And thanks for this project, I use it every day 👍

### PR DESCRIPTION
**Pull request by fpietka**
## Description
Adding `application_name` to help identify `pgcli` connections to postgres.

Fix #868

## Checklist
- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by fpietka** [comment]
There might be a better way, since I'm adding this a few times. I'm not sure we need it on simple `connect()` calls, so I'm gonna run some more tests, and update the PR with my results.

**Comment by fpietka** [comment]
In the end I only kept this parameter in case we are connecting to a specified host, as other cases are working fine without it (hence are displaying the `application_name` correctly)

**Comment by meeuw** [comment]
I'm trying to write a test to run `SELECT * FROM pg_stat_activity WHERE application_name = 'pgcli'` but this needs to be run by `pgcli/main.py` and not `tests/utils.py`.

**Comment by j-bennet** [comment]
@meeuw A behave test can do that.

**Comment by meeuw** [comment]
nice work @fpietka!

**Comment by VojtechVitek** [comment]
Well done, thank you guys! 🎉

**Pull request merged**
