### PR TITLE
Feature: Add new formatter to export data to sql like mycli

### PR DESCRIPTION
**Pull request by astroshot**
## Description

New formatter is added to export query result to sql-insert format and sql-update format like mycli:

For example:
```
PostgreSQL postgres@127.0.0.1:5432/test ➜ SELECT * FROM "user";
id  name     email                   phone      description  created_at                     updated_at
--  -------  ----------------------  ---------  -----------  -----------------------------  -----------------------------
1   Jackson  jackson_test@gmail.com  132454789               2022-09-09 19:44:32.712343+08  2022-09-09 19:44:32.712343+08
SELECT 1
Time: 0.028s

# Choose sql-insert output format
PostgreSQL postgres@127.0.0.1:5432/test ➜ \T sql-insert;
Changed table format to sql-insert
Time: 0.001s

# Then we have sql-insert output of query result
PostgreSQL postgres@127.0.0.1:5432/test ➜ SELECT * FROM "user";
INSERT INTO "user" ("id", "name", "email", "phone", "description", "created_at", "updated_at") VALUES
('1', 'Jackson', 'jackson_test@gmail.com', '132454789', '', '2022-09-09 19:44:32.712343+08', '2022-09-09 19:44:32.712343+08')
;
SELECT 1
Time: 0.004s

# Choose sql-update format
PostgreSQL postgres@127.0.0.1:5432/test ➜ \T sql-update;
Changed table format to sql-update
Time: 0.000s
PostgreSQL postgres@127.0.0.1:5432/test ➜ SELECT * FROM "user";
UPDATE "user" SET
"name" = 'Jackson'
, "email" = 'jackson_test@gmail.com'
, "phone" = '132454789'
, "description" = ''
, "created_at" = '2022-09-09 19:44:32.712343+08'
, "updated_at" = '2022-09-09 19:44:32.712343+08'
WHERE "id" = '1';
SELECT 1
Time: 0.004s
```

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by astroshot** [comment]
I tested this code by run `pip install -e .`. But I didn't do
> `pip install pre-commit && pre-commit install`, and ran black on my code.`

So what do I need to do before this PR is reviewed?

**Comment by j-bennet** [comment]
@astroshot We use `black` to format our code, and `pre-commit` to enforce it. The CI build will fail if the code is not black-ified.

**Comment by j-bennet** [comment]
@astroshot Your new formatter could be useful to more than just `pcli`. What do you think about moving it into `cli_helpers`?

**Comment by astroshot** [comment]
@j-bennet OK, I'll install `black` and recommit my code later.

The reason I didn't put this formatter to `cli_helpers` now is that different database use different delimiters to disambiguate table name from SQL keywords. For example, postgres uses `"` and mysql uses  back quote ` . 

For example, in postgres, insertion sql is:
```sql
INSERT INTO "user" ("id", "name", "email", "phone", "description", "created_at", "updated_at") VALUES
('1', 'Jackson', 'jackson_test@gmail.com', '132454789', '', '2022-09-09 19:44:32.712343+08', '2022-09-09 19:44:32.712343+08')
;
```

And in myql, it is:

```sql
INSERT INTO `user` (`id`, `name`, `email`, `phone`, `description`, `created_at`, `updated_at`) VALUES
('1', 'Jackson', 'jackson_test@gmail.com', '132454789', '', '2022-09-09 19:44:32.712343+08', '2022-09-09 19:44:32.712343+08')
;
```
Yet I'm not familiar with oracle and Mircosoft SQL Server.

So I'd like to merge this PR so that we can use it in `pgcli` as soon as possible. Then I'll try to move this formatter to `cli_helpers`, and use different delimiters for different database type passed from pgcli (or mycli and other clis), and it will take more time for fully test.
Do you think it's ok?

**Comment by j-bennet** [comment]
@astroshot 

> The reason I didn't put this formatter to cli_helpers now is that different database use different delimiters to disambiguate table name from SQL keywords. For example, postgres uses " and mysql uses back quote ` .

You could make your formatter configurable.

> So I'd like to merge this PR so that we can use it in pgcli as soon as possible. Then I'll try to move this formatter to cli_helpers, and use different delimiters for different database type passed from pgcli (or mycli and other clis), and it will take more time for fully test.

Sounds good to me.

Before merging, this new adapter needs some unit tests. Please add some, they don't have to be extensive.

**Comment by astroshot** [comment]
> @astroshot
> 
> > The reason I didn't put this formatter to cli_helpers now is that different database use different delimiters to disambiguate table name from SQL keywords. For example, postgres uses " and mysql uses back quote ` .
> 
> You could make your formatter configurable.
> 
> > So I'd like to merge this PR so that we can use it in pgcli as soon as possible. Then I'll try to move this formatter to cli_helpers, and use different delimiters for different database type passed from pgcli (or mycli and other clis), and it will take more time for fully test.
> 
> Sounds good to me.
> 
> Before merging, this new adapter needs some unit tests. Please add some, they don't have to be extensive.

Sure, I'll commit unit tests later.

**Comment by astroshot** [comment]
> > @astroshot
> > > The reason I didn't put this formatter to cli_helpers now is that different database use different delimiters to disambiguate table name from SQL keywords. For example, postgres uses " and mysql uses back quote ` .
> > 
> > 
> > You could make your formatter configurable.
> > > So I'd like to merge this PR so that we can use it in pgcli as soon as possible. Then I'll try to move this formatter to cli_helpers, and use different delimiters for different database type passed from pgcli (or mycli and other clis), and it will take more time for fully test.
> > 
> > 
> > Sounds good to me.
> > Before merging, this new adapter needs some unit tests. Please add some, they don't have to be extensive.
> 
> Sure, I'll commit unit tests later.

@j-bennet Hi, I have committed unit tests, is there any more work to do before merging?

**Comment by j-bennet** [comment]
You also want to add the new supported formats to `pgclirc`.

**Comment by astroshot** [comment]
> You also want to add the new supported formats to `pgclirc`.

@j-bennet New formatters have been added to `pgclirc` 😁

**Comment by j-bennet** [comment]
@astroshot Your change is now released as part of 3.5.0.

**Comment by astroshot** [comment]
> @astroshot Your change is now released as part of 3.5.0.

@j-bennet Thanks 😁

**Pull request merged**
