### PR TITLE
Move literal definitions to standalone files

### PR DESCRIPTION
**Pull request by darikg**

### CODE REVIEW

**Comment by darikg** [comment]
It looks like the tests are failing because the .txt files aren't being copied to the site-packages directory:

```
IOError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pgcli/packages/pgliterals/keywords.txt'
```

**Comment by amjith** [comment]
I've modified setup.py file to include the txt files from pgliterals folder. 

Should we make the flat files into json files? They are quite simple and straight forward right now, but I feel like making them JSON files would give them a bit of a structure. We can make them into an array: 

```
['ACCESS',
'ADD',
'ALL,
...
]
```

We can use the `json` [library](https://docs.python.org/2/library/json.html) that is available in the standard library to read the file.

**Comment by j-bennet** [comment]
What is the reason to make them text and not a python structure (array or dict) in a separate file?

**Comment by amjith** [comment]
I speak for myself and not for @darikg's intentions on this matter. I think the advantage of a text file is that it'll be easy for someone to add new entries without understanding Python. Not that python code is hard to read or understand, but adding things to a json file or a txt file is less intimidating to a non-python user. 

I also envision a day when we can allow users to supply their own custom files which can live anywhere (such as ~/.pgliterals for example). In which case it is better to have them as flat files instead of python source.

@darikg Your thoughts?

**Comment by darikg** [comment]
@j-bennet Mostly just habit to try to separate code and data. Like @amjith said, long-term we'd like users to be able to override literal definitions somewhere, and having arbitrary executable code in config files tends to lead to trouble.

@amjith Thanks! I didn't realize setup.py was responsible for packaging data like that, but it makes sense. json makes sense too -- I guess that would suggest moving all the literals into a single file, like

```
{
    'keywords': [
        'ACCESS',
        'ADD',
        'ALL,
        ...
    ],
    'functions': [
        'AVG',
        'COUNT',
        ...
```

**Comment by amjith** [comment]
@darikg I didn't think about collapsing it into a single file. That's not a bad idea. It'll be easier in the future to have a single file to override instead of multiple files.

**Comment by j-bennet** [comment]
I see. I kind of think that pgcli's audience being developers, they would figure out a python array. Just like moving styles into pgcli config was not a problem. But yes, json in single file sounds like the best option, especially if it eventually goes into user's home directory.

**Comment by darikg** [comment]
Ok, I moved everything to a single json file, but now I'm getting timeout errors from the behavioral tests...

**Comment by j-bennet** [comment]
Do the tests run locally?

**Comment by darikg** [comment]
I don't know - I haven't been able to get behave to work on Windows. But the rest of the tests pass, and the CLI works normally, so I can't even guess what else broke.

**Comment by darikg** [comment]
It looks like pexpect 4.0 just got released today so I'm suspecting that's the culprit

**Comment by j-bennet** [comment]
@darikg I think it's best to remove those tests from travis temporarily. Too much breakage lately. I may need to rethink  / find other ways to do functional testing.

@amjith Thoughts?

**Comment by j-bennet** [comment]
@darikg Functional tests fail for me locally, which is a good sign. I will try to figure out what's going on.

**Comment by amjith** [comment]
Please don't remove the behave tests from Travis. In the past month every failure on behave has caught a bug.

eg:

1. `~/.config` folder had to be created using the `makedirs` calls.
2. prompt_toolkit 0.52 had a broken prompt, which caused this bug #370.

Both of them are real issues. I do NOT want to disable the tests. I know it adds delay to our process but I think it is a small delay compared to the person-cycles we'll have to waste if we released something buggy and had to answer github issues all day.

**Comment by amjith** [comment]
Obligatory caveat, if everyone feels it does more good by disabling, please feel free to ignore my objections.

**Comment by j-bennet** [comment]
@darikg I made a couple of small fixes in tests and it seems to help. Would that be a problem if I check that in to this branch?

**Comment by j-bennet** [comment]
@amjith Those are good points. I'm probably too sensitive to tests breaking because they were my addition in the first place, so each time this happens I feel like I put a spoke in other people's wheel. They do have their use though, so I'd only disable them if I can't fix them.

**Comment by j-bennet** [comment]
This will be problematic though:

https://travis-ci.org/dbcli/pgcli/jobs/83729711#L166

It seems like new `pexpect` requires `ptyprocess` and that's not available in 2.6. I may need to pin the version of `pexpect`.

**Comment by darikg** [comment]
Yeah I'm with @amjith - I'd hate to lose the behavioral tests. Can we pin everything to the last set of working versions?

**Comment by j-bennet** [comment]
@darikg I think so, I'll look at it tonight. But I'd still want to include my current fix.

**Comment by j-bennet** [comment]
This PR includes integration tests fixes: https://github.com/dbcli/pgcli/pull/375

**Comment by darikg** [comment]
@j-bennet sorry, you meant also you had fixes specific to this PR? feel free to push them up

**Comment by j-bennet** [comment]
@darikg No, it's all specific to pexpect, and included in #375.

**Comment by darikg** [comment]
Ok, @j-bennet fixed everything. This PR is reporting as still failing tests even after retriggering a build, but that's just because of https://github.com/travis-ci/travis-ci/issues/1485.

**Comment by j-bennet** [comment]
Pretty. It should certainly make adding new keywords less annoying.

**Comment by amjith** [comment]
The behave tests are passing for me locally. 

I'm going to merge this PR.

**Comment by j-bennet** [comment]
Thanks @amjith.

**Pull request merged**
