### PR TITLE
Add pg_service.conf handling

### PR DESCRIPTION
**Pull request by gantsevdenis**
## Description

This implements https://github.com/dbcli/pgcli/issues/1083

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by j-bennet** [comment]
@gantsevdenis Can you take a look at those conflicts in `main.py`?

**Comment by gantsevdenis** [comment]
@j-bennet done!

**Comment by j-bennet** [comment]
👍 FInally had the chance to try this - works as expected. Thanks!

**Comment by ptwales** [comment]
Can I close #1083 now?

**Pull request merged**
