### PR TITLE
Upgrade to prompt-toolkit-0.57

### PR DESCRIPTION
**Pull request by jonathanslenders**
A new pull request with the minimal set of changes required to run on the latest prompt_toolkit.
This doesn't enable new features yet (like mouse support.)

(Not tested on Windows.)

### CODE REVIEW

**Comment by amjith** [comment]
@darikg Can you test this on Windows? 

I'm currently testing it on OS X.

**Comment by amjith** [comment]
Pasting works as expected without additional indentation. :)

**Comment by darikg** [comment]
Works fine for me. I still get extra indentation pasting stuff though

**Comment by jonathanslenders** [comment]
Hi @darikg,

That is expected. Bracketed paste is a vt100 option and only works on OS X, Linux and Unix. Maybe for Windows we can think of a different approach, but for now, it is like that.

Jonathan

**Comment by darikg** [comment]
Fair enough!

**Comment by amjith** [comment]
If there are no objections, I'd like to merge it in the morning.

**Comment by j-bennet** [comment]
+1

**Comment by darikg** [comment]
:+1:

**Pull request merged**
