### PR TITLE
Fix test_config.py on Windows

### PR DESCRIPTION
**Pull request by ERYoung11**
## Description
I'm developing on Windows with VS Code.  test_config.py failed for the final case as setting a directory to read-only did not prevent writing to that directory on Windows.  I have updated the code to try name the subdir with an illegal character which prevents the creation of rcfile.  I used the double-quote character.  This character is legal on Linux.  This test now passes on Linux (when run as non-root) and Windows.

Wrappager was also marked as changed due to, I'm guessing, some hidden characters.  I have checked it in with this too.  As you can see, github thinks there are no changes to the file.

## Checklist

- [ ] I've added this contribution to the `changelog.rst`.
- [ ] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by ERYoung11** [comment]
I'm no expert here, but I don't think this should have failed due to timeout as this was a very insignificant change.

**Comment by j-bennet** [comment]
@ERYoung11 Yes, I don't think the test failure was related to your change. Thank you for the PR! Feel free to update changelog / authors file, or I can merge it as-is if you prefer.

**Comment by ERYoung11** [comment]
Go ahead and merge.  If I do something more significant I'll update those sections.  I'm currently looking at Issue #1240.  

Also, is the vagrant file out of date?  I can't find the chef/centos & chef/debian it's asking for.  I could fix that up too.

Is there somewhere that I can chat about these sorts of questions?  Fair warning, I'm sort of a newbie (and old newbie working to learn new tricks).

**Comment by j-bennet** [comment]
> If I do something more significant I'll update those sections. I'm currently looking at Issue #1240.

Sounds good to me. Any and all contributions are appreciated.

> Also, is the vagrant file out of date? I can't find the chef/centos & chef/debian it's asking for. I could fix that up too.

Yes, it is quite outdated. If you're willing to take on updating it, please do.

> Is there somewhere that I can chat about these sorts of questions? Fair warning, I'm sort of a newbie (and old newbie working to learn new tricks).

We prefer to communicate via github issues. This gives us more visibility on when a contributor drops the ball / loses interest in the issue (happens all the time unfortunately), and someone else can pick it up, because all the context is there.

**Pull request merged**
