### PR TITLE
Added support for PyPy using psycopg2cffi

### LINKED ISSUE #140: Add support for pypy
Right now pgcli won't work in pypy because psycopg2 won't install for pypy. But there is psycopg2cffi for pypy.

### PR DESCRIPTION
**Pull request by thedrow**
I run the tests once and some of them fail.
Let's see what the build says.
This PR fixes #140.

### CODE REVIEW

**Comment by thedrow** [comment]
Strange, it fails locally for me:
```
tox -re pypy
GLOB sdist-make: /home/omer/Documents/pgcli/setup.py
pypy recreate: /home/omer/Documents/pgcli/.tox/pypy
pypy installdeps: pytest, mock
pypy inst: /home/omer/Documents/pgcli/.tox/dist/pgcli-0.18.0.zip
pypy installed: cffi==1.1.0,click==4.1,configobj==5.0.6,funcsigs==0.4,greenlet==0.4.7,mock==1.3.0,pbr==1.3.0,pgcli==0.18.0,prompt-toolkit==0.42,psycopg2cffi==2.7.1,py==1.4.30,Pygments==2.0.2,pytest==2.7.2,readline==6.2.4.1,six==1.9.0,sqlparse==0.1.14,wcwidth==0.1.4,wheel==0.24.0
pypy runtests: PYTHONHASHSEED='3292657099'
pypy runtests: commands[0] | py.test
================================================================================================ test session starts ================================================================================================
platform linux2 -- Python 2.7.9[pypy-2.6.0-final] -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/omer/Documents/pgcli, inifile: 
collected 279 items 

pgcli/packages/pgspecial/tests/test_specials.py .....
tests/test_expanded.py .
tests/test_fuzzy_completion.py ..
tests/test_naive_completion.py ....
tests/test_parseutils.py ............x.............
tests/test_pgexecute.py ................FFFF..............................................EEE.EE...........
tests/test_pgspecial.py .........
tests/test_smart_completion_multiple_schemata.py .................
tests/test_smart_completion_public_schema_only.py ..........................
tests/test_sqlcompletion.py .....................................................x....................................................

====================================================================================================== ERRORS =======================================================================================================
__________________________________________________________________________________ ERROR at setup of test_describe_special[x.*-df] __________________________________________________________________________________

connection = <psycopg2cffi._impl.connection.Connection object at 0x00000000025ffd30>

    @pytest.fixture
    def executor(connection):
        return pgcli.pgexecute.PGExecute(database='_test_db', user=POSTGRES_USER,
>               host=POSTGRES_HOST, password=None, port=None)

tests/conftest.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/pypy/site-packages/pgcli/pgexecute.py:149: in __init__
    self.connect()
.tox/pypy/site-packages/pgcli/pgexecute.py:164: in connect
    port=unicode2utf8(port))
.tox/pypy/site-packages/psycopg2cffi/__init__.py:104: in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:884: in _connect
    return connection_factory(dsn)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:134: in __init__
    self._connect_sync()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <psycopg2cffi._impl.connection.Connection object at 0x00000000025ffd48>

    def _connect_sync(self):
        self._pgconn = libpq.PQconnectdb(self.dsn.encode('utf-8'))
        if not self._pgconn:
            raise exceptions.OperationalError('PQconnectdb() failed')
        elif libpq.PQstatus(self._pgconn) == libpq.CONNECTION_BAD:
>           raise self._create_exception()
E           OperationalError: sorry, too many clients already

.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:143: OperationalError
__________________________________________________________________________________ ERROR at setup of test_describe_special[x.*-dT] __________________________________________________________________________________

    @pytest.yield_fixture(scope="function")
    def connection():
        create_db('_test_db')
>       connection = db_connection('_test_db')

tests/conftest.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:12: in db_connection
    conn = psycopg2.connect(user=POSTGRES_USER, host=POSTGRES_HOST, database=dbname)
.tox/pypy/site-packages/psycopg2cffi/__init__.py:104: in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:884: in _connect
    return connection_factory(dsn)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:134: in __init__
    self._connect_sync()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <psycopg2cffi._impl.connection.Connection object at 0x0000000002e299b8>

    def _connect_sync(self):
        self._pgconn = libpq.PQconnectdb(self.dsn.encode('utf-8'))
        if not self._pgconn:
            raise exceptions.OperationalError('PQconnectdb() failed')
        elif libpq.PQstatus(self._pgconn) == libpq.CONNECTION_BAD:
>           raise self._create_exception()
E           OperationalError: sorry, too many clients already

.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:143: OperationalError
_________________________________________________________________________________ ERROR at setup of test_describe_special[x.*-+-di] _________________________________________________________________________________

    @pytest.yield_fixture(scope="function")
    def connection():
>       create_db('_test_db')

tests/conftest.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:45: in create_db
    with db_connection().cursor() as cur:
tests/utils.py:12: in db_connection
    conn = psycopg2.connect(user=POSTGRES_USER, host=POSTGRES_HOST, database=dbname)
.tox/pypy/site-packages/psycopg2cffi/__init__.py:104: in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:884: in _connect
    return connection_factory(dsn)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:134: in __init__
    self._connect_sync()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <psycopg2cffi._impl.connection.Connection object at 0x0000000002e7a968>

    def _connect_sync(self):
        self._pgconn = libpq.PQconnectdb(self.dsn.encode('utf-8'))
        if not self._pgconn:
            raise exceptions.OperationalError('PQconnectdb() failed')
        elif libpq.PQstatus(self._pgconn) == libpq.CONNECTION_BAD:
>           raise self._create_exception()
E           OperationalError: sorry, too many clients already

.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:143: OperationalError
_________________________________________________________________________________ ERROR at setup of test_describe_special[x.*-+-ds] _________________________________________________________________________________

    @pytest.yield_fixture(scope="function")
    def connection():
        create_db('_test_db')
>       connection = db_connection('_test_db')

tests/conftest.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:12: in db_connection
    conn = psycopg2.connect(user=POSTGRES_USER, host=POSTGRES_HOST, database=dbname)
.tox/pypy/site-packages/psycopg2cffi/__init__.py:104: in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:884: in _connect
    return connection_factory(dsn)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:134: in __init__
    self._connect_sync()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <psycopg2cffi._impl.connection.Connection object at 0x00000000029e7e80>

    def _connect_sync(self):
        self._pgconn = libpq.PQconnectdb(self.dsn.encode('utf-8'))
        if not self._pgconn:
            raise exceptions.OperationalError('PQconnectdb() failed')
        elif libpq.PQstatus(self._pgconn) == libpq.CONNECTION_BAD:
>           raise self._create_exception()
E           OperationalError: sorry, too many clients already

.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:143: OperationalError
_________________________________________________________________________________ ERROR at setup of test_describe_special[x.*-+-df] _________________________________________________________________________________

    @pytest.yield_fixture(scope="function")
    def connection():
>       create_db('_test_db')

tests/conftest.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:45: in create_db
    with db_connection().cursor() as cur:
tests/utils.py:12: in db_connection
    conn = psycopg2.connect(user=POSTGRES_USER, host=POSTGRES_HOST, database=dbname)
.tox/pypy/site-packages/psycopg2cffi/__init__.py:104: in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:884: in _connect
    return connection_factory(dsn)
.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:134: in __init__
    self._connect_sync()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <psycopg2cffi._impl.connection.Connection object at 0x00000000034aab90>

    def _connect_sync(self):
        self._pgconn = libpq.PQconnectdb(self.dsn.encode('utf-8'))
        if not self._pgconn:
            raise exceptions.OperationalError('PQconnectdb() failed')
        elif libpq.PQstatus(self._pgconn) == libpq.CONNECTION_BAD:
>           raise self._create_exception()
E           OperationalError: sorry, too many clients already

.tox/pypy/site-packages/psycopg2cffi/_impl/connection.py:143: OperationalError
===================================================================================================== FAILURES ======================================================================================================
_____________________________________________________________________________________ test_json_renders_without_u_prefix[True] ______________________________________________________________________________________

executor = <pgcli.pgexecute.PGExecute object at 0x00007f48508f9b08>, expanded = True

    @requires_json
    def test_json_renders_without_u_prefix(executor, expanded):
        run(executor, "create table jsontest(d json)")
        run(executor, """insert into jsontest (d) values ('{"name": "Éowyn"}')""")
        result = run(executor, "SELECT d FROM jsontest LIMIT 1",
>                    join=True, expanded=expanded)

tests/test_pgexecute.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:66: in run
    expanded=expanded))
.tox/pypy/site-packages/pgcli/main.py:466: in format_output
    output.append(expanded_table(cur, headers))
.tox/pypy/site-packages/pgcli/packages/expanded.py:15: in expanded_table
    for row in rows:
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:569: in __iter__
    rows = self.fetchmany(self.itersize)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:30: in check_closed_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:43: in check_no_tuples_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:355: in fetchmany
    return [self._build_row() for _ in xrange(size)]
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:891: in _build_row
    self._casts[i], val, length, self)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:71: in typecast
    return caster.cast(value, cursor, length)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:38: in cast
    return self.py_caster(value, cursor)
.tox/pypy/site-packages/psycopg2cffi/_json.py:182: in typecast_json
    return loads(s)
.tox/pypy/site-packages/pgcli/pgexecute.py:187: in _json_typecaster
    return json_data.decode(self.conn.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

input = '{"name": "Éowyn"}', errors = 'strict'

    def decode(input, errors='strict'):
>       return codecs.utf_8_decode(input, errors, True)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 10: ordinal not in range(128)

.tox/pypy/lib-python/2.7/encodings/utf_8.py:16: UnicodeEncodeError
_____________________________________________________________________________________ test_json_renders_without_u_prefix[False] _____________________________________________________________________________________

executor = <pgcli.pgexecute.PGExecute object at 0x00000000024d3478>, expanded = False

    @requires_json
    def test_json_renders_without_u_prefix(executor, expanded):
        run(executor, "create table jsontest(d json)")
        run(executor, """insert into jsontest (d) values ('{"name": "Éowyn"}')""")
        result = run(executor, "SELECT d FROM jsontest LIMIT 1",
>                    join=True, expanded=expanded)

tests/test_pgexecute.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:66: in run
    expanded=expanded))
.tox/pypy/site-packages/pgcli/main.py:469: in format_output
    missingval='<null>'))
.tox/pypy/site-packages/pgcli/packages/tabulate.py:885: in tabulate
    list_of_lists, headers = _normalize_tabular_data(tabular_data, headers)
.tox/pypy/site-packages/pgcli/packages/tabulate.py:586: in _normalize_tabular_data
    rows = list(tabular_data)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:569: in __iter__
    rows = self.fetchmany(self.itersize)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:30: in check_closed_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:43: in check_no_tuples_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:355: in fetchmany
    return [self._build_row() for _ in xrange(size)]
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:891: in _build_row
    self._casts[i], val, length, self)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:71: in typecast
    return caster.cast(value, cursor, length)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:38: in cast
    return self.py_caster(value, cursor)
.tox/pypy/site-packages/psycopg2cffi/_json.py:182: in typecast_json
    return loads(s)
.tox/pypy/site-packages/pgcli/pgexecute.py:187: in _json_typecaster
    return json_data.decode(self.conn.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

input = '{"name": "Éowyn"}', errors = 'strict'

    def decode(input, errors='strict'):
>       return codecs.utf_8_decode(input, errors, True)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 10: ordinal not in range(128)

.tox/pypy/lib-python/2.7/encodings/utf_8.py:16: UnicodeEncodeError
_____________________________________________________________________________________ test_jsonb_renders_without_u_prefix[True] _____________________________________________________________________________________

executor = <pgcli.pgexecute.PGExecute object at 0x00000000034cd7f8>, expanded = True

    @requires_jsonb
    def test_jsonb_renders_without_u_prefix(executor, expanded):
        run(executor, "create table jsonbtest(d jsonb)")
        run(executor, """insert into jsonbtest (d) values ('{"name": "Éowyn"}')""")
        result = run(executor, "SELECT d FROM jsonbtest LIMIT 1",
>                    join=True, expanded=expanded)

tests/test_pgexecute.py:179: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:66: in run
    expanded=expanded))
.tox/pypy/site-packages/pgcli/main.py:466: in format_output
    output.append(expanded_table(cur, headers))
.tox/pypy/site-packages/pgcli/packages/expanded.py:15: in expanded_table
    for row in rows:
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:569: in __iter__
    rows = self.fetchmany(self.itersize)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:30: in check_closed_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:43: in check_no_tuples_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:355: in fetchmany
    return [self._build_row() for _ in xrange(size)]
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:891: in _build_row
    self._casts[i], val, length, self)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:71: in typecast
    return caster.cast(value, cursor, length)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:38: in cast
    return self.py_caster(value, cursor)
.tox/pypy/site-packages/psycopg2cffi/_json.py:182: in typecast_json
    return loads(s)
.tox/pypy/site-packages/pgcli/pgexecute.py:187: in _json_typecaster
    return json_data.decode(self.conn.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

input = '{"name": "Éowyn"}', errors = 'strict'

    def decode(input, errors='strict'):
>       return codecs.utf_8_decode(input, errors, True)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 10: ordinal not in range(128)

.tox/pypy/lib-python/2.7/encodings/utf_8.py:16: UnicodeEncodeError
____________________________________________________________________________________ test_jsonb_renders_without_u_prefix[False] _____________________________________________________________________________________

executor = <pgcli.pgexecute.PGExecute object at 0x0000000003630218>, expanded = False

    @requires_jsonb
    def test_jsonb_renders_without_u_prefix(executor, expanded):
        run(executor, "create table jsonbtest(d jsonb)")
        run(executor, """insert into jsonbtest (d) values ('{"name": "Éowyn"}')""")
        result = run(executor, "SELECT d FROM jsonbtest LIMIT 1",
>                    join=True, expanded=expanded)

tests/test_pgexecute.py:179: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:66: in run
    expanded=expanded))
.tox/pypy/site-packages/pgcli/main.py:469: in format_output
    missingval='<null>'))
.tox/pypy/site-packages/pgcli/packages/tabulate.py:885: in tabulate
    list_of_lists, headers = _normalize_tabular_data(tabular_data, headers)
.tox/pypy/site-packages/pgcli/packages/tabulate.py:586: in _normalize_tabular_data
    rows = list(tabular_data)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:569: in __iter__
    rows = self.fetchmany(self.itersize)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:30: in check_closed_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:43: in check_no_tuples_
    return func(self, *args, **kwargs)
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:355: in fetchmany
    return [self._build_row() for _ in xrange(size)]
.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py:891: in _build_row
    self._casts[i], val, length, self)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:71: in typecast
    return caster.cast(value, cursor, length)
.tox/pypy/site-packages/psycopg2cffi/_impl/typecasts.py:38: in cast
    return self.py_caster(value, cursor)
.tox/pypy/site-packages/psycopg2cffi/_json.py:182: in typecast_json
    return loads(s)
.tox/pypy/site-packages/pgcli/pgexecute.py:187: in _json_typecaster
    return json_data.decode(self.conn.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

input = '{"name": "Éowyn"}', errors = 'strict'

    def decode(input, errors='strict'):
>       return codecs.utf_8_decode(input, errors, True)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 10: ordinal not in range(128)

.tox/pypy/lib-python/2.7/encodings/utf_8.py:16: UnicodeEncodeError
============================================================================= 4 failed, 268 passed, 2 xfailed, 5 error in 4.50 seconds ==============================================================================
ERROR: InvocationError: '/home/omer/Documents/pgcli/.tox/pypy/bin/py.test'
```

**Comment by amjith** [comment]
Looks like those failing tests are getting skipped in Travis. :(

**Comment by amjith** [comment]
You might have to grep through the code for occurrences of psycopg2 and change them all. Some of the tests still use psycopg2 and pgexecute.py uses psycopg2.

**Comment by amjith** [comment]
This PR is invalid.

**Comment by thedrow** [comment]
I should try again someday.

**Pull request closed without merging**
