### PR TITLE
Minimal fix for #590

### PR DESCRIPTION
**Pull request by darikg**
issue #590

### CODE REVIEW

**Comment by darikg** [comment]
This probably isn't the correct thing to do -- numeric formatting shouldn't apply to string types, even if they look like numbers. But it looks like tabulate is happy to treat strings as numbers if they look like numbers

**Comment by foxyterkel** [comment]
I thought about definition of value type. Is it right to define '1234' like int? Could be better to make some fixes in _column_type method? But @darikg  decision will work to.

**Comment by darikg** [comment]
@foxyterkel agreed. I updated the PR

**Comment by amjith** [comment]
Thanks @darikg!

🔨

**Pull request merged**
