### PR TITLE
Simplify config file handling.

### PR DESCRIPTION
**Pull request by amjith**
Reduce the complexity of config files. 

Reviewer: @j-bennet

### CODE REVIEW

**Comment by j-bennet** [comment]
@amjith It doesn't need an expanduser call anymore?

**Comment by amjith** [comment]
Good catch. It does need the expanduser call. I'll update the PR.

**Comment by amjith** [comment]
Updated.

**Comment by j-bennet** [comment]
So, default config can be None. In that case, things won't break, but you'll be creating and merging an unnecessary empty ConfigObj. I think adding an "if" is better, even though it makes the code less pretty.

**Comment by amjith** [comment]
I tested the None case and made a conscious decision to create an empty ConfigObj. Objects are cheap and I value code clarity. :)

**Comment by j-bennet** [comment]
Fair enough.

**Pull request merged**
