### PR TITLE
[Proposal] Fpietka/pep8

### PR DESCRIPTION
**Pull request by fpietka**
## Description
Attempt to solve all PEP8 related issues

## Checklist
- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by fpietka** [comment]
@dbcli/pgcli-core I took care of splitting each type of change so we can discuss together if this is something we want, or partially want.

This is of course open for discussion.

**Comment by j-bennet** [comment]
Whoa @fpietka, that's one large PR! Out of curiosity, what prompted it?

**Comment by j-bennet** [comment]
@fpietka I don't mind the rest of the fixes, but I would rather not enforce [binary operator position](https://github.com/dbcli/pgcli/pull/809/commits/64771cb8e4a875bfbaf083df2c08ed543c08ef9a). @dbcli/pgcli-core - any strong opinions here? We can move the discussion to slack if you prefer.

**Comment by meeuw** [comment]
@j-bennet my opinion is that we should avoid "multi-line-one-liners" in the first place.

**Comment by j-bennet** [comment]
@meeuw What do you replace those with? :)

**Comment by meeuw** [comment]
It really depends, `if`'s with long conditions could be rewritten by introducting some variables:
```
if (prev_tok and prev_tok.value and
        prev_tok.value.lower().split(' ')[-1] == 'using'):
```
could be rewritten to (A):
```
lastword = prev_tok.value.lower().split(' ')[-1]
if (prev_tok and prev_tok.value and lastword == 'using'):
```
or, using nested `if`'s (B)
```
if (prev_tok and prev_tok.value):
    if prev_tok.value.lower().split(' ')[-1] == 'using'):
```
I think this improves the readability and could help when running the code in a debugger.

I'd prefer (A) btw.

Oh I think this is mostly nitpicking, I'd propose to rewrite this only when doing serious refactors and even then; I think I'd be guilty to add conditions "as a oneliner" as well...

**Comment by bersace** [comment]
@meeuw 👍 

*Readability counts.*

**Comment by bersace** [comment]
> Oh I think this is mostly nitpicking, I'd propose to rewrite this only when doing serious refactors and even then; I think I'd be guilty to add conditions "as a oneliner" as well...

👍 too. Don't pollute commit history with lintwar :-)

**Comment by fpietka** [comment]
@j-bennet what triggered it is one part my editor prompting me the issues, one (big) part my OCD ^^ also I found pep8radius failing me from time to time.
Concerning the binary operator position, maybe we can than change/ignore the rule.

@dbcli/pgcli-core concerning multiline splits I didn't make any decision, nor have strong preference. I think it would be nice to agree on a pattern for the code to come (and we can discard what I've done here) since linter do not enforce anything.

I wasn't intending a lint-war, so I limited my changes to the lint rule of the project and I have no problem discarding part/all of the changes. For myself I'm more interested in the discussion we are now having to know where everybody stand 😁

**Comment by j-bennet** [comment]
To me, these fixes can be split into 2 main groups:

1. Changes that improve code readability.
* Blank lines.
* Whitespaces.
* Adding two spaces before inline comment.
* Removing accidental duplicated spaces.
* Removing unnecessary backslash.
* Fixing long lines.
* Removing unused imports/vars.

2. Changes that are a matter of taste.
* Binary operator position.
* Replacing lambda with def

I'd fix Group 1 and skip Group 2.

**Pull request closed without merging**
