### PR TITLE
setup.py: license='BSD'

### PR DESCRIPTION
**Pull request by msabramo**
More useful to see on PyPI.

### CODE REVIEW

**Comment by amjith** [comment]
I have vendored in the Tabulate package, which is licensed under MIT. This might change in the future when a new version of Tabulate is released that has the changes I need.

So I wouldn't want to blanket it under BSD without the author's consent.

**Comment by msabramo** [comment]
Gotcha.

**Comment by amjith** [comment]
I don't think we'll do this for a while, since we've vendored in OrderedDict now. I'm going to close this for now.

**Comment by amjith** [comment]
@msabramo It took us a while, but we're finally ready to call pgcli 'BSD' licensed. We're no longer packaging in tabulate library. 

Looks like the PR has grown outdated, but rest assured I'll be updating the setup.py with your change. 

Thank you!

**Pull request closed without merging**
