### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by hraban**
Simple Dockerfile to allow running this tool in docker. I've tested it manually, but I can't get the automated test suite to run. I've been trying to, but I don't want to let this linger while I work on that.

### CODE REVIEW

**Comment by hraban** [comment]
If you want to test it, I've uploaded a build to dockerhub:

```
docker run --rm -ti luyat/pgcli:docker pgcli --help
```

**Comment by hraban** [comment]
(more comments more comments)

With this you can create a dockerhub account yourself and create an automated build for pgcli. That way, people don't have to download or install anything (if they have docker), they can just do `docker run --rm -ti dbcli/pgcli pgcli -something -something`.

**Comment by j-bennet** [comment]
Very interesting. I dockerized pgcli before, to test it on different OS:

https://github.com/j-bennet/dockerized

but didn't realize other people may want to do that also.

There should be more detailed instructions about how to use it. For example, I have a database called `boo`. I normally connect like this:

```
$ pgcli boo
```

But when I run with the docker container, no such luck:

```
$ docker run --rm -ti luyat/pgcli:docker pgcli boo
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by hraban** [comment]
Is boo a host name defined in your /etc/hosts?

**Comment by j-bennet** [comment]
No, this is actually a database name. I connect to database boo on localhost.

**Comment by j-bennet** [comment]
What I was getting at, pgcli running in docker probably needs ports forwarded, and possibly a UNIX socket bound, and maybe changes in postgres config to allow external TCP connections.

**Comment by j-bennet** [comment]
@hraban I think this PR is fine to merge, but it needs a little more information in readme about running `pgcli` in docker. I'd probably explain why a user may want to do that ("in case you want to try out pgcli without installing it on your system..."), and what additional steps may be required for pgcli to connect from under docker container ("you postgres server should allow external TCP/IP connections...").

**Comment by hraban** [comment]
yes, good points. sorry for not getting back on this. I'll try to write something up.

in related news, if you use `--net host` you can connect to a postgresql server running (and listening) on localhost:

```
docker run --rm -ti --net host luyat/pgcli:docker pgcli -h localhost
```

And if your postgresql DB is, itself, running in docker, you could mount it from a shared named volume:

```
docker run -v pgsock:/var/run/postgresql postgres
# and:
docker run --rm -ti -v pgsock:/var/run/postgresql luyat/pgcli:docker pgcli
```

I haven't tested running postgresql DB as a first-class app on your host, mounting host /var/run/postgresql to a docker host and connecting through that, but it... might work?? probably? needs testing.

anyway this all needs proper writing up but it's something to play with.

**Comment by hraban** [comment]
Done and rebased onto master.

**Comment by j-bennet** [comment]
@hraban Looks great - thank you! Please add your name to [authors](https://github.com/dbcli/pgcli/blob/master/AUTHORS) and your contribution to the "Upcoming" ones in [changelog](https://github.com/dbcli/pgcli/blob/master/changelog.rst), and I'll merge it.

**Comment by j-bennet** [comment]
Thanks a lot!

**Comment by hraban** [comment]
haha we just pushed and merged simultaneously :D

**Comment by hraban** [comment]
no p. also, this is completely up to you, but a great next step would be to create a "automated build" in hub.docker.com. It will make it even easier for people to try out pgcli---just one docker line, done. no git clone or docker build.

anyway thanks for taking the time. cheers!

**Comment by j-bennet** [comment]
@hraban If you're willing to take care of that, we'll definitely appreciate it!

**Comment by hraban** [comment]
gladly, but we'll need to coordinate auth between github and dockerhub. shoot me an e-mail at hraban@0brg.net and I can help you through the process.

**Pull request merged**
