### PR TITLE
Changelog update to release 2.0.0.

### PR DESCRIPTION
**Pull request by j-bennet**
Changelog update to release 2.0.0.

The only change is updating to prompt-toolkit 2.0.

### CODE REVIEW

**Comment by amjith** [comment]
:tada:

**Comment by j-bennet** [comment]
Perfect. Now, to do the actual release. :)

**Comment by j-bennet** [comment]
@lhw, would you be able to release the new pgcli debian package? It would be good to release one for 1.11.0 also (previous version).

**Comment by j-bennet** [comment]
@lhw Just a fyi, 2.0.1 is the latest of pgcli now. I must be missing something about prompt-toolkit? Latest released prompt-toolkit is 2.0.7, and pgcli would have no problem with it.

**Comment by lhw** [comment]
I only checked the setup.py not the actual prompt_toolkit repo, thought there were some compatibility issues. I did the prompt_toolkit update on debian today. Will have to see what needs to be done to get it up-to-date in debian unstable. There were some changes and there could be hard dependencies on versions <2.0.0 in which case i need to make some changes.
Also yes the version i have locally is already 2.0.1. This was just the last thread i was cited in.

**Pull request merged**
