### PR TITLE
Use psycopg2 to get database details

### LINKED ISSUE #765: Prompt hostname when using `service=`
## Description
When connecting with `pgcli` "normally", i.e. `pgcli -h hostname...`, upon connection the prompt usually shows the hostname:app which is extremely useful given that I'm often connected to multiple production databases.

However, when using `service=servicename` with the same details, the prompt instead shows IP address:database. This makes it very difficult to see at a glance which database I'm connected to.

Is there any config that I'm missing or is that the nature of using service to connect -- the hostname information is lost?

## Your environment

- [x] Ubuntu 16.10
- [x] 1.7.0
- [x] What is the output of ``pip freeze`` command.
chardet==2.3.0
click==6.7
colorama==0.3.9
command-not-found==0.3
defer==1.0.6
distro-info===0.14build1
docopt==0.6.2
feedparser==5.2.1
gitsome==0.7.2
greenlet==0.4.12
language-selector==0.1
lightdm-gtk-greeter-settings==1.2.1
lxml==3.6.4
Mako==1.0.4
MarkupSafe==0.23
msgpack-python==0.4.8
neovim==0.1.13
numpydoc==0.6.0
pexpect==4.2.0
Pillow==3.3.1
ply==3.10
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pycups==1.9.73
Pygments==2.2.0
pygobject==3.22.0
python-apt==1.1.0b5
python-debian==0.1.29
pytz==2016.10
pyxdg==0.25
PyYAML==3.11
reportlab==3.3.0
requests==2.10.0
six==1.10.0
ssh-import-id==5.6
ubuntu-drivers-common==0.0.0
ufw==0.35
uritemplate==3.0.0
uritemplate.py==3.0.2
urllib3==1.15.1
usb-creator==0.3.3
wcwidth==0.1.7
xkit==0.0.0

### PR DESCRIPTION
**Pull request by fpietka**
## Description
Use psycopg2 to get database details when connected.

Fix #765 

## Checklist
- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by amjith** [comment]
This is a good idea. I'd like to do some manual testing to make sure we're not introducing any change in behavior. I'll do a bit of testing today and hopefully merge it in tonight.

**Comment by fpietka** [comment]
Ok. I think it can be used to get the `\conninfo` from #716 pretty easily too.

(I restarted one of the travis tests, it seems it randomly timeout the exact same test everytime)

**Comment by j-bennet** [comment]
Nice one.

**Comment by j-bennet** [comment]
Works great for me when connecting with `-D`:

```
(pgcli) --- src/pgcli ‹fpietka/get-infos-when-dsn› » pgcli -D logproc
Version: 1.7.0
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
logproc@lo.co.com:logproc>
```

However, I get an error when connecting without `-D` and with `-h`:

```
(pgcli) --- src/pgcli ‹fpietka/get-infos-when-dsn› » pgcli -h localhost postgres
ERROR:  No such database: postgres
ERROR:  No such database: postgres
```

I for sure have a database `postgres`. I don't know if the error is connected to this PR, but looks like a bug in any case.

**Comment by fpietka** [comment]
It's odd as this code is supposed to be executed only when DSN is passed. 
Let me check that one.

**Comment by fpietka** [comment]
Can't reproduce that one. Can you check again with the master?

**Comment by j-bennet** [comment]
Will do.

**Comment by j-bennet** [comment]
I checked out master, and the error disappeared. I checked out your branch again, and the error is not there anymore. Not sure what it was! But I think you're good. :)

**Comment by amjith** [comment]
Can one of you check if this affects the reconnect behavior? 
I'm not able to verify things at the moment. If that checks out this PR is good to merge .

**Comment by j-bennet** [comment]
I don't think this kind of a change would affect reconnecting, but if it did, how would you test it?

**Comment by j-bennet** [comment]
So I let pgcli sit idle and then when I tried to run a query I got this:

```
2017-07-29 16:17:08,926 (32692/MainThread) pgcli.main ERROR - sql: u"select source, started, apikeys, rq_job_id from  rebuild_jobs_beta where finished is null and started > '2017-07-28' limit 100;", error: InterfaceError('connection already closed',)
2017-07-29 16:17:08,926 (32692/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/irina/src/pgcli/pgcli/main.py", line 405, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/Users/irina/src/pgcli/pgcli/main.py", line 621, in _evaluate_command\n    for title, cur, headers, status, sql, success in res:\n  File "/Users/irina/src/pgcli/pgcli/pgexecute.py", line 299, in run\n    for result in pgspecial.execute(cur, sql):\nInterfaceError: connection already closed\n'
```

I think we'll have the same problem in master though. It was just not fully fixed in https://github.com/dbcli/pgcli/pull/743. We have to handle `InterfaceError` in more than that one spot.

**Comment by j-bennet** [comment]
Verified there's the same problem with master - won't prompt me to reconnect. I think this PR is safe to merge.

**Comment by j-bennet** [comment]
Thank you! 🌹

**Pull request merged**
