### PR TITLE
Edit last-run query in external editor.

### PR DESCRIPTION
**Pull request by tsroten**
## Description

This addresses #434. It relies on https://github.com/dbcli/pgspecial/pull/33.

If a query has been run in the current session, opening the external editor `\e` will bring the last-run query into the editor. Otherwise, the editor will be blank.

The behavior remains the same for editing a current query (e.g. `select \e`).

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Related mycli pull request: https://github.com/dbcli/mycli/pull/425

**Comment by tsroten** [comment]
Tests are failing until the pgspecial change is released: https://github.com/dbcli/pgspecial/pull/33

**Comment by tsroten** [comment]
pgspecial was released, but the tests appear to be failing until #713 is merged.

**Comment by j-bennet** [comment]
This works fine, and the tests now pass also. Merging.

**Pull request merged**
