### PR TITLE
Add auto matching for SSH tunnels

### PR DESCRIPTION
**Pull request by sweenu**
## Description
This PR goes on top of https://github.com/dbcli/pgcli/pull/1301. It adds a `ssh tunnels` config section where we can auto match a regex of the DB's host to an SSH tunnel url.
With this addition, there is truly no more need for a custom script to handle tunnels, pgcli can do it all (at least in my case 😁 ).

Of course, I'll add documentation if this gets merged!

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by j-bennet** [comment]
Hi @sweenu, I rebased this PR on top of master as best I could, but some of the changes in here conflicted with https://github.com/dbcli/pgcli/pull/1301. Please take a look over this PR and let me know if you think it's ok to merge. Thank you!

**Comment by sweenu** [comment]
@j-bennet Sorry for not coming back to you sooner!
Thanks for merging my other PR. I just fixed the conflicts, so it should be ready to be merged :)
I have been using this branch for a few months now without any issue.

**Comment by j-bennet** [comment]
Thank you for the PR! I'll have a release out with your addition soon. This should be very useful.

**Comment by j-bennet** [comment]
@sweenu 3.4.0 is released with your change.

**Pull request merged**
