### PR TITLE
Added humanized time display. Connect #396.

### PR DESCRIPTION
**Pull request by j-bennet**
This is a small change to add humanized time display in parentheses.

Examples:

```
Time: 0.006s (a moment)
Time: 10.005s (10 seconds)
Time: 120.011s (2 minutes)
```

### CODE REVIEW

**Comment by amjith** [comment]
The change works as expected. But I'm not sure I like the fact it says 'a moment' for time deltas under a second. 

I suspect that most of the sql commands execute in under a second and it's going to keep showing `a moment` in parenthesis for most of them. 

My preference would be to fork humanize and vendor it in inside our packages folder and make necessary edits to support sub-second formatting. 

What do you think?

**Comment by j-bennet** [comment]
@amjith I'm thinking for sub-second queries, this humanized display does not really add any new information, so no point even forking the lib. How about I only show this display for queries that last more than a second?

**Comment by amjith** [comment]
Yes. I think that's a good idea.

**Comment by j-bennet** [comment]
Examples after new change:

```
Time: 0.502s
Time: 1.002s (a second)
Time: 10.009s (10 seconds)
```

**Comment by amjith** [comment]
Looks good. :koala:

**Pull request merged**
