### PR TITLE
Add support for using pspg as the pager.

### PR DESCRIPTION
**Pull request by pmav99**
addresses #1102

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by j-bennet** [comment]
@pmav99 You could combine your two PRs, they are both related to the same issue!

Please add the changes to changelog, and they'll be good to merge. Thank you!

**Comment by pmav99** [comment]
@j-bennet Is there a way to retrieve the `table_format` runtime setting? I am asking because here we get the configuration option, which might have changed in the meantime with `\T <supported_table_format>`:
https://github.com/dbcli/pgcli/pull/1173/commits/3d48597fa66a9ca4322c270cd6169ccca9f17c8e#diff-38f3aeda57742756afa677ca09dcea43R1076

**Comment by j-bennet** [comment]
@pmav99 When table format is set during runtime, it would be set in cli instance, `self.table_format`:

https://github.com/dbcli/pgcli/blob/3071de14f55f7ea1a3df2dd5f42800363e225d2a/pgcli/main.py#L326

So it should be `self.table_format`, vs `self.config["main"]["table_format"]`.

**Comment by pmav99** [comment]
Perfect! thank you @j-bennet . I rebased.

**Comment by j-bennet** [comment]
Looks good. Merging - thank you! 🍓

**Pull request merged**
