### PR TITLE
[WIP] Fix for PQconninfo not available.

### PR DESCRIPTION
**Pull request by j-bennet**
## Description

Fix for #1110 PQconninfo not available in libpq < 9.3.

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by amjith** [comment]
Why is this marked as WIP?

**Comment by j-bennet** [comment]
@amjith I have no way to test it, I have newer postgresql and libpq, that's why it's WIP.

**Comment by amjith** [comment]
I was able to reproduce the issue using a docker image.

I have made a small change to the PR to check for libpq version instead of psycopg2 version. 

@j-bennet If you're happy with the changes I've made, please feel free to merge it.

**Comment by j-bennet** [comment]
@amjith I think that we'd still need to check psycopg2 version, not libpq version, to make sure `conn.info.dsn_parameters` is present, because that object is provided by psycopg2. What do you think?

**Comment by amjith** [comment]
You might be right. We will have to check both versions. When I tried your PR yesterday, pgcli won't even start even though psycopg2 version was the latest by libpq version was 9.1. 

I'll update the PR to check for both.

**Comment by amjith** [comment]
Actually we have psycopg2 version requirement in setup.py, so I don't think we need to do the psycopg2 version check during runtime. Thoughts?

**Comment by j-bennet** [comment]
> Actually we have psycopg2 version requirement in setup.py, so I don't think we need to do the psycopg2 version check during runtime.

Ha. Ok, that will do it. Except that we currently require 2.7.4 and up:

https://github.com/dbcli/pgcli/blob/199a0223e044ec3116879e67d2b924050e4afa78/setup.py#L20

so we should probably change it to 2.8 and up. Otherwise we'll have an exception with versions in between 2.7.4 and 2.8 (pypi has 2.7.5, 2.7.6, 2.7.6.1, 2.7.7).

**Comment by amjith** [comment]
:+1:

**Pull request merged**
