### PR TITLE
Refresh completions after COMMIT or ROLLBACK.

### PR DESCRIPTION
**Pull request by j-bennet**
## Description

We have to refresh completions after COMMIT or ROLLBACK, since those may change the database schema. See also #711.

## Checklist

- [X] I've added this contribution to the `changelog.md`.
- [X] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by amjith** [comment]
I think the tests are failing because of pep8radius but I can't tell why.

**Comment by j-bennet** [comment]
Yes, I'll have a look tomorrow.

**Comment by tsroten** [comment]
Looks like pep8radius wanted a period at the end of the sentence 😲 

This seem to work great 😄 . Merged.

**Comment by amjith** [comment]
> Looks like pep8radius wanted a period at the end of the sentence

That's the most hilarious flagging of a violation. I didn't realize pep8radius was such a grammar police. ;)

**Pull request merged**
