### PR TITLE
add explain visualizer

### PR DESCRIPTION
**Pull request by dkuku**
## Description
adds a formatter for explain analyze output
based on https://github.com/dkuku/pyev
## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by dkuku** [comment]
tbh I have no idea whats the best way to write tests for it ?

**Comment by amjith** [comment]
The explain plan looks gorgeous. :smile: 

I'm still playing around with it, haven't had a chance to look through the code yet. 

Looks like some of the colors you've used from click aren't available in the older versions of click. So we should consider requiring a modern version of click in setup.py.

**Comment by amjith** [comment]
@dkuku Instead of binding the explain mode to F5 key can we detect an EXPLAIN query and automatically display the results using ExplainVisualizer?

**Comment by dkuku** [comment]
@amjith we can but you need to pass some params to the explain query and when these are missing it may crash due to missing fields or the format (it needs json). I was tinking more of having an easy way to show the explain for your current query. I think its more useful than having a way to switch between vim/emacs mode with a shortcut because you use one or the other?

**Comment by j-bennet** [comment]
Hey @dkuku, sorry it's been forever since you submitted this PR, but I think it's good to merge. Would you be able to rebase it on top of main and resolve the conflicts?

**Comment by dkuku** [comment]
Hi @j-bennet I merged master into this branch.

**Comment by j-bennet** [comment]
Merged. Nice work! 🍫

**Pull request merged**
