### PR TITLE
add optional but default squash merge request to PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by meeuw**
## Description
add optional but default squash merge request to PULL_REQUEST_TEMPLATE

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.

### CODE REVIEW

**Comment by j-bennet** [comment]
Why not disallow merge commits instead? Is there a reason we want those?

**Comment by meeuw** [comment]
I'm not sure if it's possible to disallow merge commits on github. But I guess you mean why I've made it optional. There are use cases for merge commits (like multiple authors, nicely crafted commits etc) and I'd like to warn contributors that their commits will be squashed.

**Comment by j-bennet** [comment]
We can disable merge commits in repo settings:

image

I wish there was a way to choose the default merge button option, but it does not look like it. Even so, I wrote to github support and asked the question, let's see what they say.

**Comment by meeuw** [comment]
Good find! Looking forward to the support reply.

**Comment by j-bennet** [comment]
Ok, let's start with asking nicely. Hopefully Github will add the "default merge button" feature at some point.

**Pull request merged**
