### PR TITLE
Add fallback queries so that redshift auto-complete indexing doesn't exception out

### PR DESCRIPTION
**Pull request by timcleaver**
I have added fallback queries that allow the auto-completion indexing to not exception out with the current version of Amazon Redshift. Only tested to a "works for me" state.

### CODE REVIEW

**Comment by amjith** [comment]
@timcleaver Thanks for taking the time to do the PR. I appreciate it. Unfortunately I don't have Redshift to test this against.

A cursory glance at the code changes look good to me. 

@darikg Can you take a look at this as well? I know you've spent some time on the meta commands as well.

**Comment by darikg** [comment]
I like the idea of developing alternative metadata queries so we can support different versions of postgresql. I think ideally we'd check what version of postgresql we're running against and then choose an appropriate set of queries, instead of catching psycopg2.ProgrammingErrors and resorting to the fallback. That would make it easier to expand going forward, and also help a lot in comparing the different versions of the queries against each other.

**Comment by amjith** [comment]
I agree that we should check the version string to determine the set of queries to run. 

@timcleaver Would you mind adding that check? You can use the `server_version` attribute in the connection object. http://initd.org/psycopg/docs/connection.html#connection.server_version

**Comment by timcleaver** [comment]
Sure, let me look into it.

**Comment by timcleaver** [comment]
I have pushed a change to use the server_version as requested. Not sure what is going on with Travis CI though.

**Comment by amjith** [comment]
Don't worry about the test failure, I made a bad merge that broke the tests. :(

I've tested the changes in my local installation and the current functionality is not broken. I haven't tested it in RedShift, but I presume you've done the due diligence here. 

@darikg Any objections before I merge? If I don't hear back from you, I'll merge it in the morning.

**Comment by darikg** [comment]
If you don't mind, give me an extra day to look it over

**Comment by amjith** [comment]
Take your time, I'll wait for you to give me a thumbs up.

**Comment by darikg** [comment]
I had a VM with postgresql 8.4 installed, and I can connect and everything seems fine.
I ran the pgexecute tests locally and most stuff passed. The failures look pretty cursory. If we're going for 'soft support' of postgresql 8 I think this is fine. It's too bad travis-ci doesn't support older versions of postgresql so we could move towards official support.

Related issues where people were interested in support for pg8: #414, #316, #167, #18

Test failures:

```
executor = <pgcli.pgexecute.PGExecute object at 0x00000000041F5BE0>

    @dbtest
    def test_conn(executor):
        run(executor, '''create table test(a text)''')
        run(executor, '''insert into test values('abc')''')
>       assert run(executor, '''select * from test''', join=True) == dedent("""\
            +-----+
            | a   |
            |-----|
            | abc |
            +-----+
            SELECT 1""")
E       assert '+-----+\n| a ...-----+\nSELECT' == '+-----+\n| a ...--+\nSELECT 1'
E         Skipping 35 identical leading characters in diff, use -v to show
E           ---+
E         - SELECT
E         + SELECT 1
E         ?       ++

executor   = <pgcli.pgexecute.PGExecute object at 0x00000000041F5BE0>

C:\Users\dg\Documents\python\pgcli\tests\test_pgexecute.py:15: AssertionError
F
executor = <pgcli.pgexecute.PGExecute object at 0x0000000005ACF2B0>

    @dbtest
    def test_bools_are_treated_as_strings(executor):
        run(executor, '''create table test(a boolean)''')
        run(executor, '''insert into test values(True)''')
>       assert run(executor, '''select * from test''', join=True) == dedent("""\
            +------+
            | a    |
            |------|
            | True |
            +------+
            SELECT 1""")
E       assert '+------+\n| a...-----+\nSELECT' == '+------+\n| a...--+\nSELECT 1'
E         Skipping 40 identical leading characters in diff, use -v to show
E           ---+
E         - SELECT
E         + SELECT 1
E         ?       ++

executor   = <pgcli.pgexecute.PGExecute object at 0x0000000005ACF2B0>

C:\Users\dg\Documents\python\pgcli\tests\test_pgexecute.py:27: AssertionError
F.
executor = <pgcli.pgexecute.PGExecute object at 0x00000000041FACF8>

    @dbtest
    def test_functions_query(executor):
        run(executor, '''create function func1() returns int
                         language sql as $$select 1$$''')
        run(executor, 'create schema schema1')
        run(executor, '''create function schema1.func2() returns int
                         language sql as $$select 2$$''')
    
        run(executor, '''create function func3()
                         returns table(x int, y int) language sql
                         as $$select 1, 2 from generate_series(1,5)$$;''')
    
        run(executor, '''create function func4(x int) returns setof int language sql
                         as $$select generate_series(1,5)$$;''')
    
        funcs = set(executor.functions())
>       assert funcs >= set([
            FunctionMetadata('public', 'func1', '',
                             'integer', False, False, False),
            FunctionMetadata('public', 'func3', '',
                             'TABLE(x integer, y integer)', False, False, True),
            FunctionMetadata('public', 'func4', 'x integer',
                             'SETOF integer', False, False, True),
            FunctionMetadata('schema1', 'func2', '',
                             'integer', False, False, False),
          ])
E       assert set([FunctionMetadata(schema_name=u'pg_catalog', func_name=u'bytealt', arg_list='', return_type=u'bool', is_aggregate=..._name=u'character_length', arg...turn_type=u'int4', is_aggregate=False, is_window=False, is_set_returning=False), ...]) >= set([FunctionMetadata(schema_name='public', func_name='func1', arg_list='', return_type='integer', is_aggregate=False,..._name='func4', arg_list='x integer'...pe='SETOF integer', is_aggregate=False, is_window=False, is_set_returning=True)])
E        +  where set([FunctionMetadata(schema_name='public', func_name='func1', arg_list='', return_type='integer', is_aggregate=False,..._name='func4', arg_list='x integer'...pe='SETOF integer', is_aggregate=False, is_window=False, is_set_returning=True)]) = set([FunctionMetadata(schema_name='public', func_name='func1', arg_list='', return_type='integer', is_aggregate=False, is_...', func_name='func2', arg_list='', return_type='integer', is_aggregate=False, is_window=False, is_set_returning=False)])

executor   = <pgcli.pgexecute.PGExecute object at 0x00000000041FACF8>
funcs      = set([FunctionMetadata(schema_name=u'pg_catalog', func_name=u'bytealt', arg_list='', return_type=u'bool', is_aggregate=..._name=u'character_length', arg...turn_type=u'int4', is_aggregate=False, is_window=False, is_set_returning=False), ...])

C:\Users\dg\Documents\python\pgcli\tests\test_pgexecute.py:82: AssertionError
F..........
executor = <pgcli.pgexecute.PGExecute object at 0x0000000004494198>

    @dbtest
    def test_bytea_field_support_in_output(executor):
        run(executor, "create table binarydata(c bytea)")
        run(executor,
            "insert into binarydata (c) values (decode('DEADBEEF', 'hex'))")
    
>       assert u'\\xdeadbeef' in run(executor, "select * from binarydata", join=True)
E       assert '\xdeadbeef' in '+------------------+\n| c                |\n|------------------|\n| \336\255\276\357 |\n+------------------+\nSELECT'
E        +  where '+------------------+\n| c                |\n|------------------|\n| \336\255\276\357 |\n+------------------+\nSELECT' = run(<pgcli.pgexecute.PGExecute object at 0x0000000004494198>, 'select * from binarydata', join=True)

executor   = <pgcli.pgexecute.PGExecute object at 0x0000000004494198>

C:\Users\dg\Documents\python\pgcli\tests\test_pgexecute.py:175: AssertionError
```

**Comment by amjith** [comment]
@darikg Awesome work testing it on a VM. Much appreciated. 

I'd prefer to fix the test failures if possible but if you think they're too hard to fix or too time consuming to investigate I'm fine with doing a soft support. 

I'll leave this PR in your capable hands to merge when you feel ready.

**Comment by darikg** [comment]
I think I'm just going to merge this in - I'll try to get around to looking at the test failures eventually but I think they're mild enough it's not worth holding up soft pg8 support.

**Comment by darikg** [comment]
Thanks @timcleaver !

**Pull request merged**
