### PR TITLE
python3.8: add travis test and setup.py class.

### PR DESCRIPTION
**Pull request by laixintao**
## Description

test in python38.

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by laixintao** [comment]
Why did @codecov-io think the coverage is decreased?

**Comment by laixintao** [comment]
So I think the decrease is because we didn't test in Python3.8 before, the comparison isn't useful. I saw a decrease in https://github.com/dbcli/mycli/pull/837#pullrequestreview-376958583  too.

image

**Comment by j-bennet** [comment]
@laixintao Aren't we all cutting edge now... :)

**Comment by pasenor** [comment]
Apparently it does drop, both here and in mycli. I have calculated percentages for individual reports, it looks like this ([script is here](https://gist.github.com/pasenor/a257f374b5cd074ce73525cb75f030c3)):
```
mycli 3.6: 78.64%
mycli 3.7: 78.64%
mycli 3.8: 48.09%

pgcli 3.6: 83.99%
pgcli 3.7: 83.99%
pgcli 3.8: 56.70%
```
Don't yet know why.

**Pull request merged**
