### PR TITLE
Possible fix for redshift?

### PR DESCRIPTION
**Pull request by darikg**
cf #537 
not tested
bugfix: don't call att.atttypid::regtype::text in old versions of postgresql

### CODE REVIEW

**Comment by jklukas** [comment]
Here's what I get when I try out this version on Redshift:
```
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
analytics> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrr
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrn
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 115, in refresh_functions
    completer.extend_functions(executor.functions())
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgcompleter.py", line 160, in extend_functions
    for f in func_data:
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgexecute.py", line 478, in functions
    cur.execute(query)
ProgrammingError: column "proallargtypes" does not exist in p, n, unnamed_join
```

**Comment by jklukas** [comment]
Fetched the changes and see the following on Redshift:
```
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
analytics> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrr
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrn
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 115, in refresh_functions
    completer.extend_functions(executor.functions())
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgcompleter.py", line 160, in extend_functions
    for f in func_data:
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgexecute.py", line 492, in functions
    cur.execute(query)
ProgrammingError: function array_length(oidvector, integer) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type cast.
```

**Comment by darikg** [comment]
Here's hoping the third try's the charm

**Comment by jklukas** [comment]
```
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
analytics> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrr
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrn
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 115, in refresh_functions
    completer.extend_functions(executor.functions())
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgcompleter.py", line 160, in extend_functions
    for f in func_data:
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgexecute.py", line 492, in functions
    cur.execute(query)
ProgrammingError: column p.proargmodes does not exist
```

**Comment by darikg** [comment]
I'm terrible at this

**Comment by jklukas** [comment]
I'm still seeing the same error after updating with the latest commit:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrr
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/thrn
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/Users/jeffklukas/Code/pgcli/pgcli/completion_refresher.py", line 115, in refresh_functions
    completer.extend_functions(executor.functions())
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgcompleter.py", line 160, in extend_functions
    for f in func_data:
  File "/Users/jeffklukas/Code/pgcli/pgcli/pgexecute.py", line 492, in functions
    cur.execute(query)
ProgrammingError: column p.proargmodes does not exist
```

**Comment by darikg** [comment]
Can you try again? I think I missed committing something

**Comment by jklukas** [comment]
It works! I'm getting valid table name completions on Redshift. 👍

**Comment by darikg** [comment]
:fireworks:

**Comment by amjith** [comment]
Nice job shooting with a blindfold while riding a horse and landing on target.

**Comment by j-bennet** [comment]
Wow @darikg. Just wow.

**Comment by amjith** [comment]
I'm going to merge this and do a quick bug fix release. 🍐

**Comment by jcox92** [comment]
Does this automatically get pushed to pypi or will I need to install from source?

**Comment by amjith** [comment]
You will have to install from master. Please use: 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

I haven't released it to PyPI yet. It'll take a day or two.

**Pull request merged**
