### PR TITLE
Support unicode strings in notices.

### PR DESCRIPTION
**Pull request by amjith**
A simple use case is when someone uses unicode characters in a RAISE statement.

Example: 

```
DO language plpgsql $$
BEGIN
  RAISE NOTICE '有人更改';
END
$$;
```

I've added a test. 

Reviewer: @stuartquin

### CODE REVIEW

**Comment by amjith** [comment]
I'm not sure why the tests are failing on Travis. I wonder if it has to do with Postgres versions available in Travis.

**Comment by amjith** [comment]
I give up. I have no clue why this is failing since it passes just fine on my local machine. Can one of you verify that it indeed passes the test suite locally? 

@dbcli/pgcli-core

**Comment by stuartquin** [comment]
Looks alright locally:
```
298 passed, 91 skipped, 1 xfailed, 1 xpassed in 4.91 seconds 
```
Can also confirm the functionality works

**Comment by stuartquin** [comment]
Just realized I didn't run the pgexecute tests - doh

**Comment by stuartquin** [comment]
Still looks good though 
```
================================================================================ 389 passed, 1 xfailed, 1 xpassed in 7.37 seconds =================================================================================
```

**Comment by darikg** [comment]
Different version of psycopg2 on travis maybe?

**Comment by darikg** [comment]
Nevermind, I don't think that's it. The passes locally for me with psycopg2=2.6.1, but still fails when forcing travis to run with 2.6.1.

**Comment by amjith** [comment]
I've disabled the test to make it pass. I tried it on various operating systems and tried pinning the psycopg2 version, no luck. I'm going to write this off as a Travis CI anomaly. 

Can one of you merge this please?

**Pull request merged**
