### PR TITLE
Fix issue #919

### PR DESCRIPTION
**Pull request by lelit**

### CODE REVIEW

**Comment by lelit** [comment]
AFAICT the failure is not related to my changes... that OTOH I think aren't even tested by Travis: we should activate a _matrix_ to check against different version of PostgreSQL. One project I know doing that is [asyncpg](https://github.com/MagicStack/asyncpg/blob/master/.travis.yml#L40).

**Comment by j-bennet** [comment]
@lelit Yes, that test failure is intermittent, things are fine now. Would you be able to rebase this PR on top of master? Otherwise, it looks good to me.

**Comment by lelit** [comment]
There it is, thank you!

**Comment by j-bennet** [comment]
👍 Looks good. Merging!

**Pull request merged**
