### PR TITLE
Drop python 3.7, add 3.12

### PR DESCRIPTION
**Pull request by j-bennet**
## Description

* Drop python 3.7.
* Add python 3.12.
* Other housekeeping.

Blocker:

* https://github.com/sdispater/pendulum/issues/696

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by laixintao** [comment]
ha, sorry missed your work on python 3.12. I closed mine: https://github.com/dbcli/pgcli/pull/1428

but seems the tests on 3.12 is unstable, don't know why.

from my branch, it sometimes success sometimes fail exactly like yours. (see https://github.com/dbcli/pgcli/pull/1428/commits , no code change in last 2 commit but one failed one succeed.)

**Comment by j-bennet** [comment]
> but seems the tests on 3.12 is unstable, don't know why.
> 
> from my branch, it sometimes success sometimes fail exactly like yours. (see https://github.com/dbcli/pgcli/pull/1428/commits , no code change in last 2 commit but one failed one succeed.)

Yes! I'm trying to work around that. May just have to skip it with 3.12.

**Comment by j-bennet** [comment]
@laixintao I skipped the failing checks. The build now passes. I still want to find out what's going on, but that can be done in a follow-up PR. What do you think?

**Comment by laixintao** [comment]
Look pretty good! thanks 👍

**Pull request merged**
