### PR TITLE
add behave to tox

### PR DESCRIPTION
**Pull request by meeuw**
## Description
add behave to tox

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- ~[ ] I've added my name to the `AUTHORS` file (or it's already there).~

### CODE REVIEW

**Comment by j-bennet** [comment]
@meeuw According to https://github.com/dbcli/mycli/pull/427, it is not necessary to multiply the number of test environments (`{pytest,behave}`), is that right?

**Comment by meeuw** [comment]
true, I've changed tox.ini but the behave scripts need some modifications (to be able to run from `PACKAGE_ROOT` instead of `tests` directory). I will create a new PR for that.

**Comment by j-bennet** [comment]
Looks good to me, but I'd like to try this out before merging. I'll do that as soon as possible.

**Comment by meeuw** [comment]
:+1: take your time.

**Comment by j-bennet** [comment]
@meeuw I'll merge it after you remove py26. :)

**Comment by meeuw** [comment]
done

**Comment by j-bennet** [comment]
👍

**Pull request merged**
