### PR TITLE
bugfix: don't echo a newline when output is empty.

### PR DESCRIPTION
**Pull request by laixintao**
## Description
fix https://github.com/dbcli/pgcli/issues/1169

## Checklist

- [ ] I've added this contribution to the `changelog.rst`.
- [ ] I've added my name to the `AUTHORS` file (or it's already there).

- [ ] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by laixintao** [comment]
before:
image


after:
image

**Comment by j-bennet** [comment]
@laixintao Good catch! Please add it to changelog as well.

**Comment by amjith** [comment]
Very nice! 

I'll update the changelog. Thanks, @laixintao! 

:wine_glass:

**Comment by laixintao** [comment]
> @laixintao Good catch! Please add it to changelog as well.
> 
> P.S. Yes, I think we want this change. It makes the output more compact, which might help if someone wants to copy it from the screen, and it aligns the behavior with other cli tools.

I think the same as well :)

@amjith Thanks for changelog :)

**Pull request merged**
