### PR TITLE
`column` keyword suggests columns

### PR DESCRIPTION
**Pull request by darikg**
E.g. so `ALTER TABLE foo ALTER COLUMN ` suggests columns from `foo`. 

@koljonen can you review & merge?

### CODE REVIEW

**Comment by amjith** [comment]
Thank you for the tests. 🎓

**Comment by koljonen** [comment]
I think **ADD COLUMN** should be excluded.

**Comment by amjith** [comment]
Actually no. We should include the suggestions for ADD COLUMN to make sure the user knows about the existence of a column similar to the one they are adding.

**Comment by darikg** [comment]
Yeah, it's consistent with how e.g. Create table suggests table names. It's actually pretty useful

**Pull request merged**
