### PR TITLE
Upgrade to prompt_toolkit==0.38

### PR DESCRIPTION
**Pull request by jonathanslenders**
Upgrade to the newest version of prompt_toolkit. This should also fix the issue with slow pasting.

Feel free to make changes to the pull request before merging.
I'm not sure how you are feeling about the circular reference between pgcli_bindings and the main class. It can be a weakref, but it doesn't have to.

### CODE REVIEW

**Comment by amjith** [comment]
I've tested this locally and it works as expected. Can the @dbcli/pgcli-core team please take it for a spin?

@darikg Can you verify that things work as expected in Windows? 

* Paste is now fast. 
* Haven't tried the fuzzy completion branch, but I'll try it soon to make sure that it doesn't crash when the entered word is longer than the suggestion.

**Comment by j-bennet** [comment]
You missed one @jonathanslenders:

https://github.com/jonathanslenders/pgcli/blob/prompt_toolkit_0.38/pgcli/main.py#L187

**Comment by jonathanslenders** [comment]
Good catch @j-bennet . I missed that one.

Pull request updated.

**Comment by j-bennet** [comment]
@jonathanslenders: I do have doubts, like you said, about passing in the whole pgcli into pgcli_bindings call, as opposed to passing in only what's necessary. What was the reasoning for doing it this way?

**Comment by jonathanslenders** [comment]
@j-bennet: The reasoning is that ``KeyBindingManager`` became stateless. It doesn't know anymore whether ``vi_mode`` is on or off by itself. It takes a ``vi_mode`` filter instance as input. In our case, that's this condition: ``Condition(lambda cli: pgcli.vi_mode)``. It's something that evaluates to a boolean when it's called, and in our case it evaluates by taking the value of ``pgcli.vi_mode``.

So what happened is that now the actual state of ``vi_mode`` is only present in the ``pgcli`` class. (I think this is what we call some simplified kind of reactive programming.)  Previously, we also had the ``vi_mode`` variable inside ``pgcli``, but that variable only contained the initial state for the manager. Every following change only updated the ``vi_mode`` variable in the manager, not in ``pgcli``. So, there we had some inconsistency.

We have two options. Either we keep this state somewhere in a settings object, and we pass that around to the code that needs to change it. Or we keep it in ``pgcli``, but pass a function to retrieve and set it. e.g.:

```python
def set_vi_mode(value):
    self.vi_mode = value

... = pgcli_bindings(get_vi_mode=lambda: self.vi_mode,
                               set_vi_mode=set_vi_mode)

```

What do you think?

**Comment by j-bennet** [comment]
@jonathanslenders I was going to suggest passing in a function. I like the lambda approach in your code snippet.

**Comment by jonathanslenders** [comment]
@j-bennet Pull request updated.

**Comment by j-bennet** [comment]
Looks great now @jonathanslenders ! Thank you for being so responsive. I will test it some more tonight to make sure nothing else is missing / breaks.

**Comment by j-bennet** [comment]
Tested again and don't see any problems. Pasting a large query is a hundred times faster (this is the query I used: https://gist.github.com/j-bennet/fac59560b017d7d77b76). I think it's good to merge when @darikg has a chance to verify things work on Windows.

**Comment by amjith** [comment]
Just tested the fuzzy completion branch. It works beautifully. :)

For the curious souls, you can check out the branch https://github.com/dbcli/pgcli/tree/amjith/fuzzy_match

You will have to run `pip install -e . ` after you pull to install new dependencies.

I'd like to have a bigger discussion about this feature before making it a default. So treat it as purely experimental.

/cc @dbcli/pgcli-core

**Comment by darikg** [comment]
Everything's cool in Windows as of jonathanslenders/python-prompt-toolkit@c3efe84a084afd8d1020edc7f587118c5c8b7642 -- maybe wait for its next Pypi release?

**Comment by jonathanslenders** [comment]
prompt_toolkit==0.39 released and pull request updated.

**Comment by amjith** [comment]
Thank you all for taking the time to contribute, review and test this PR thoroughly. I appreciate it very much. 

:candy: :camel: :tractor:

**Pull request merged**
