### PR TITLE
Logging cleanup

### PR DESCRIPTION
**Pull request by mmtj**
## Description
Fix logger strings formatting to use lazy string interpolation on few logger calls.

## Checklist

- [ ] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).
- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by amjith** [comment]
Hi @mmtj, 

Thank you for the changes. Looks like the CI build is failing because of black formatting. 

I see that you've tried to run the black formatting yourself, but it looks like it is producing different results? 

Can you tell me what version of black you're using to format things?

**Comment by mmtj** [comment]
Hi,
according to virtualenv, it is `19.10b0`.

```
$ pip freeze
black==19.10b0
```

**Comment by amjith** [comment]
Looks like the CI is also using the same black version. 

Relevant section from the CI build:

```
Successfully installed appdirs-1.4.3 black-19.10b0 pathspec-0.6.0 regex-2019.8.19 typed-ast-1.4.0
would reformat /home/travis/build/dbcli/pgcli/pgcli/magic.py
would reformat /home/travis/build/dbcli/pgcli/release.py
would reformat /home/travis/build/dbcli/pgcli/tests/features/db_utils.py
would reformat /home/travis/build/dbcli/pgcli/tests/features/fixture_utils.py
would reformat /home/travis/build/dbcli/pgcli/tests/features/environment.py
would reformat /home/travis/build/dbcli/pgcli/tests/features/wrappager.py
```

Can you try running black on your branch one more time?

**Comment by amjith** [comment]
:dango:

**Pull request merged**
