### PR TITLE
Add key bindings to consistently move up and down in history

### PR DESCRIPTION
**Pull request by petobens**
## Description

Closes https://github.com/dbcli/pgcli/issues/1004

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.

### CODE REVIEW

**Comment by j-bennet** [comment]
Looks good, and seems to work just fine. Please add your contribution to changelog and authors file, so I can merge it. We ask for formatting things with `black` as well, but I see your PR does not fail the build check.

Thank you!

https://github.com/dbcli/pgcli/blob/master/changelog.rst
https://github.com/dbcli/pgcli/blob/master/AUTHORS

🌟

**Comment by petobens** [comment]
Added change and authors entries.

**Comment by j-bennet** [comment]
Lovely! Merging.

**Comment by j-bennet** [comment]
Thank you for the PR! 🍒

**Comment by petobens** [comment]
Thank you!

**Pull request merged**
