### PR TITLE
Fix \e

### PR DESCRIPTION
**Pull request by jdpopkin**

### CODE REVIEW

**Comment by jdpopkin** [comment]
There's probably a better way to do this, or at least a better place to put this code. Do let me know. (Or just close it and fix it in a cleaner way; I just want my pgcli to work again 😿)

This fixes #668 by working around changes introduced by jonathanslenders/python-prompt-toolkit@9030182.

**Comment by jdpopkin** [comment]
Actually, there's a place where pgcli expects a reset to happen: https://github.com/dbcli/pgcli/pull/669/files#diff-38f3aeda57742756afa677ca09dcea43R446

So maybe we should overwrite cli.accept_action both before and after that call to cli.run. But that sounds awkward to me.

**Comment by j-bennet** [comment]
Perhaps @jonathanslenders could advise.

**Comment by jonathanslenders** [comment]
@j-bennet: What is the actual problem this is supposed to solve? I don't completely understand it.

**Comment by jonathanslenders** [comment]
Ok, I see what's going on.
One possibility would be to use indeed a custom ``AcceptAction``. But rather then calling ``set_return_value``, check whether the input equals ``\e``. If so, call ``buffer.open_in_editor``. If not, return as usual. (like ``AcceptAction.RETURN_DOCUMENT`` does.)

**Comment by jdpopkin** [comment]
Closing this in favor of #670 - thanks, everyone! 🎈

**Pull request closed without merging**
