### PR TITLE
Update suggestion literals

### PR DESCRIPTION
**Pull request by GUIEEN**
## Description

Current datatype / function suggestions based on the pgliterals.json is out of date.
So I chose to update datatypes / functions of pgliterals.json according to current version's document.

- datatypes(https://www.postgresql.org/docs/current/datatype.html)
    - Table 8.1. Data Types
    - Table 8.26. Object Identifier Types
    - Table 8.27. Pseudo-Types
- functions(https://www.postgresql.org/docs/current/functions.html)
    - Table 9.3. Comparison Functions
    - Table 9.5. Mathematical Functions
    - Table 9.9. SQL String Functions and Operators
    - Table 9.10. Other String Functions
    - Table 9.12. SQL Binary String Functions and Operators
    - Table 9.13. Other Binary String Functions
    - Table 9.24. Formatting Functions
    - Table 9.31. Date/Time Functions
    - Table 9.33. Enum Support Functions
    - Table 9.35. Geometric Functions
    - Table 9.36. Geometric Type Conversion Functions
    - Table 9.38. cidr and inet Functions
    - Table 9.52. Array Functions
    - Table 9-42. General-Purpose Aggregate Functions
    - Table 9-44. General-Purpose Window Functions

- [x] Updated function / database test cases

## Checklist

- [x] I've added this contribution to the `changelog.rst`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

- [x] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by j-bennet** [comment]
@GUIEEN Thank you for the PR! It looks like you need to update unit tests as well. Are you able to do that?

**Comment by GUIEEN** [comment]
okay, I can look into it but not sure how should the test logic be done.
do you think is it enough to check whether all types/funcs I added is loaded well on the suggestions or not ?

**Comment by j-bennet** [comment]
Sorry it took me a while to get back - this is looking great! Merging.

**Comment by GUIEEN** [comment]
no problem ! it's my pleasure :)

**Pull request merged**
