### PR TITLE
Added \echo & \qecho for Issue #1335

### PR DESCRIPTION
**Pull request by ERYoung11**
## Description

I added a simple \echo & \qecho command.  \echo always prints to STDOUT per the documentation.  \qecho prints to the current query output stream per the documentation

## Checklist

- [X] I've added this contribution to the `changelog.rst`.
- [X] I've added my name to the `AUTHORS` file (or it's already there).

- [X] I installed pre-commit hooks (`pip install pre-commit && pre-commit install`), and ran `black` on my code.
- [x] Please squash merge this pull request (uncheck if you'd like us to merge as multiple commits)

### CODE REVIEW

**Comment by ERYoung11** [comment]
@j-bennet @amjith Any issues with this PR that I can address?  (besides that changelog.rst now has a conflict)

**Review by j-bennet — APPROVED** [review]
LGTM.

**Comment by ERYoung11** [comment]
@j-bennet @amjith  This PR is ready.  Sorry for the delay!

**Comment by ERYoung11** [comment]
Great point!  I'll rework it and resubmit.

**Comment by j-bennet** [comment]
So, `pgspecial` didn't happen :), but I merged the PR. It's a nice feature. Thank you @ERYoung11 !

**Pull request merged**
