### PR TITLE
More integration tests

### PR DESCRIPTION
**Pull request by j-bennet**
Create and drop database.
Connect and disconnect from database.
Create and drop table.
Insert, update, select from table.

### CODE REVIEW

**Comment by Abscond63** [comment]
#300 could possibly be bank COID Minnesota which was updated to 009: in bank file, RTN or ABA 091000019 routing transit number converted back in Wires 2000, approximately around date of 1997  prior to WCP wire common platform AIX conversion.  Any questions possibly contact Michael Krause at wire transfer services Wells Fargo.  Denver tech center,  Michael.krause@Wellsfargo.com.  I believe this is a LU issue with the bank file and the RTN since then has changed on the tables and should reflect 12th district of Fed, RTN 121000248.  Bank ID 121:, I have experienced the issue prior with Mike in production on call to the host system for bank ID 091000019, but prior to year 2000.  On trek and crashed LU then on secure ID flashed all 8888888, and had to return card and trek VPN connection.  Ray was also on line when tested in production at wire transfer services.  It is a bank table cross-reference issue, almost sure of.

Hope this helps.  Not sure if he is still employed at Wells.  
I am not employed there currently.  Left in 2012.  It is a issue if not corrected and drops line and system if not corrected. Bank 000 is even worse.
Thank you,

Sharon L Doherty 

On Jul 28, 2015, at 11:26, landscape-bot <notifications@github.com> wrote:


Code quality remained the same when pulling 22670a8 on dbcli:j-bennet/integration-tests into f39eb99 on dbcli:master.

**Comment by amjith** [comment]
Yeah I saw that in another PR too. This is bizzare. I'm going to delete the comment and block that user.

**Comment by amjith** [comment]
The changes look good. Could you add this to run as part of the travis build? 

Thanks for the additional tests. :)

**Comment by amjith** [comment]
@j-bennet Will you have time to update the PR to run the integration tests as part of travis or should I look into it?

**Comment by j-bennet** [comment]
I will.

**Comment by j-bennet** [comment]
Those are now in travis.

**Comment by amjith** [comment]
Thank you for making them part of Travis build. 

:computer:

**Pull request merged**
